### ISSUE TITLE
[Toast] ArkToast.Group does not exist

### ISSUE THREAD

**Issue by allysontsoares** [cschroeter/park-ui#101]
I think that the docs for toast component is not updated.
I'm using "@ark-ui/react": "^1.1.0",' and there's an issue with ArkToast.Group.

![image](https://github.com/cschroeter/park-ui/assets/110117326/299e17bd-12e4-4b3a-bedc-e66562c19cb9)

**Comment by cschroeter** [comment]
@allysontsoares 

Thanks for taking your time to create this issue. This part actually exists within the `createToater` helper fn. I will export this part in the next release. For now you can simply kill that line.
