### ISSUE TITLE
feat: expose non-standard components (e.g. Icon, Text, Heading) for solid and vue

### ISSUE THREAD

**Issue by hamzaabamboo** [cschroeter/park-ui#108]
I am trying to use Park-UI in new project and followed the steps in the documentation for implementing components such as Heading or Text, but encountered a problem that children won't render properly. 

According to [Vue Documentation](https://vuejs.org/guide/extras/render-function#passing-slots), slots, a.k.a children, are handled slightly differently for vue components (the slots are passed through context variable). 

Code samples in [Park-UI documentation](https://park-ui.com/docs/panda/components/text).
```ts
import { styled, type HTMLStyledProps } from 'styled-system/jsx'

type As = 'p' | 'span' | 'div' | 'label'

export type TextProps = {
  as?: As
} & HTMLStyledProps<As>

export const Text = (props: TextProps) => {
  const { as = 'p', ...rest } = props
  const Component = styled(as)

  return <Component {...rest} />
}
```

Fixed version, passing slots from context parameters to children.
```ts
import {
    styled,
    type HTMLStyledProps
} from 'styled-system/jsx'
import type { Events, SetupContext } from 'vue'

type As = 'p' | 'span' | 'div' | 'label'

export type TextProps = {
    as?: As
} & HTMLStyledProps<As>

export const Text = (
    props: TextProps,
    { slots }: SetupContext<Events>
) => {
    const { as = 'p', ...rest } = props
    const Component = styled(as)

    return (
        <Component {...rest}>{slots}</Component>
    )
}

export default Text
```

I just started using vue and no means a vue expert, but I suppose the code samples needs an update ? 
I also created a sample [stackblitz](https://stackblitz.com/edit/github-9ptx4p-dhrj4p?file=components%2Fui%2Ftext-fixed.tsx) to demonstrate both versions just incase.

Thank you very much.

**Comment by cschroeter** [comment]
Implemented
