### ISSUE TITLE
[Icon] Issue No ReactElement type in solid

### ISSUE THREAD

**Issue by Ns2Kracy** [cschroeter/park-ui#109]
There is no type named ReactElement in solid-js.

**Comment by sholzmayer** [comment]
Can you be more precise and give an example or a sandbox where this issue happens? Just had a look in the cli registry, so there is no ReactElement used.

**Comment by Ns2Kracy** [comment]
The original example is:

```
import { ark } from '@ark-ui/solid'
import type { ReactElement } from 'solid'
import { styled, type HTMLStyledProps } from 'styled-system/jsx'
import { icon, type IconVariantProps } from 'styled-system/recipes'

export interface IconProps extends IconVariantProps, HTMLStyledProps<'svg'> {
  children: ReactElement
}

const StyledIcon = styled(ark.svg, icon)

export const Icon = (props: IconProps) => {
  return <StyledIcon asChild {...props} />
}
```

And it shows like this:
![image](https://github.com/cschroeter/park-ui/assets/89824014/f3685b90-c87b-48e9-884e-e815b592dc23)

**Comment by Ns2Kracy** [comment]
Maybe that's how solidjs's version should be:

```
export interface IconProps extends IconVariantProps, HTMLStyledProps<'svg'> {
    children: import("solid-js").JSX.Element;
}
```

**Comment by cschroeter** [comment]
@Ns2Kracy 

Thanks for taking your time to create this issue. Closing this in faovur of #108
