### ISSUE TITLE
[docs] How to add a new framework

### ISSUE THREAD

**Issue by gabrielgrant** [cschroeter/park-ui#112]
What is involved in adding support for another framework?  (beyond support in Ark and Panda)

From a quick look, it appears 3 main things are needed:

1. the main framework-specific integration point is `create-style-context.tsx`
2. updating docs
3. updating CLI
 
Any specific pointers on what exactly needs to be done for each of these?

Anything else I'm missing?

Thanks!

For reference:
https://github.com/search?q=repo%3Acschroeter%2Fpark-ui+vue+%28NOT+path%3A%22examples%2F%22%29+AND+%28NOT+path%3A%22website%2F%22%29&type=code

**Comment by cschroeter** [comment]
@gabrielgrant 

Good question. It kinda depends what framework you have in mind - a CSS Framework or an JS Framework?

**Comment by gabrielgrant** [comment]
Ah, yes, good question -- was thinking JS framework (particularly interested in Qwik)

sorry that wasn't clear

**Comment by cschroeter** [comment]
Support for Qwik would be huge. Right now you could use Qwik in conjunction with [Panda + Park UI](https://panda-docs.vercel.app/docs/installation/qwik)

But you would miss the advanced components like `DatePicker`, `Accordion`etc
For that the first step would be to add support for Qwik in [Zag-js](https://github.com/chakra-ui/zag/discussions/392) 

Everything else should be easy from there. Please let me know if you have further questions.

**Comment by gabrielgrant** [comment]
yup, seems like Panda support for basic stateless components should be able to work today (hence the question about exactly what would be entailed).

I'm investigating adding Qwik support to Zag. The main complication with that is Qwik's need to pause/serialize/resume component state. Currently poking around how to best make Zig's state machine play nice with Qwik's (de)serialization

Do you have any interest in moving forward partial support for Qwik with stateless components only? Or not unless all components are supported?

It's possible some of the styling could be applied to the qwik-ui stateless components (or just to custom native qwik components), but does not seem like that belongs in Park

**Comment by cschroeter** [comment]
@gabrielgrant 

I think for the stateless (simple) components like `Button` `Badge`, etc. there should be nothing from stopping you to use it right away. Simply setup your Tailwind or Panda project and add the park ui plugin / preset.

In that case Park UI behaves like Daisy UI (from a Tailwind perspectiv)
