### ISSUE TITLE
Cannot install any components with the CLI on Windows

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#113]
Error:
```
Failed to download utils. ENOTDIR: not a directory, mkdir 'F:\code\quintohectare\tsconfig.json/./src/lib'
 ERROR  Command failed with exit code 1: park-ui init

pnpm: Command failed with exit code 1: park-ui init
    at makeError (C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:24890:17)
    at handlePromise (C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:25461:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:210334:7)
    at async C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:219737:21
    at async main (C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:219704:34)
    at async runPnpm (C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:219960:5)
    at async C:\Users\julio\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:219952:7
```

My config:
```json
{
  "cssFramework": "panda",
  "jsFramework": "react",
  "importAliases": {
    "components": "@/components/ui",
    "utils": "@/lib"
  },
  "useReactServerComponents": true
}
```

**Comment by allysontsoares** [comment]
My is not working too (NextJS on Windows)!

"◇  Failed to download utils. ENOTDIR: not a directory, mkdir 'D:\Bemsoft\Dev\WiseLab\web\wiselab-web\tsconfig.json/./src/lib'
PS D:\Bemsoft\Dev\WiseLab\web\wiselab-web> park-ui add button
│
◇  Failed to download Button component
ENOTDIR: not a directory, mkdir 'D:\Bemsoft\Dev\WiseLab\web\wiselab-web\tsconfig.json/./src/components/ui'"

======================================
park-ui.json:
"{
  "cssFramework": "panda",
  "jsFramework": "react",
  "importAliases": {
    "components": "~/components/ui",
    "utils": "~/lib"
  },
  "useReactServerComponents": true
}"

======================================

tsconfig.json:
"{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "postcss.config.cjs"],
  "exclude": ["node_modules"]
}"

**Comment by sholzmayer** [comment]
I've just released a fix in the version 0.4.2. Can you test it? I'm not a windows user. 

```npm install @park-ui/cli -g``` should update it if you installed it with npm globally.

**Comment by juliomuhlbauer** [comment]
```
Failed to download utils. ENOTDIR: not a directory, mkdir 'F:\code\quintohectare\tsconfig.json/./src/lib'
```

**Comment by cschroeter** [comment]
Please try `0.4.3` and open a new issue if that problem persist.

**Comment by juliomuhlbauer** [comment]
It worked for me!
