### ISSUE TITLE
Syntax error when using Ruby accent color

### ISSUE THREAD

**Issue by adrbe** [cschroeter/park-ui#114]
Just updated from 0.22.0 to 0.25.0 and noticed that all my component using accent.default token no longer show color. My default accent color is Ruby and when I changed to another color (grass), it works. When I checked the token CSS varaibles in the styled-system folder, I found out that there is a syntax error for the ruby accent color for certain token (rugby instead of ruby).

Ruby color:

```typescript
presets: [
        '@pandacss/preset-base',
        createPreset({
            accentColor: 'ruby',
            grayColor: 'neutral',
            borderRadius: 'md',
        }),
    ],
```

```css
--colors-accent-default: var(--colors-rugby-9);
--colors-accent-emphasized: var(--colors-rugby-10);
--colors-accent-text: var(--colors-rugby-a11);
```
  
  Grass color:
  
```typescript
presets: [
        '@pandacss/preset-base',
        createPreset({
            accentColor: 'grass',
            grayColor: 'neutral',
            borderRadius: 'md',
        }),
    ],
```
    
```css
--colors-accent-default: var(--colors-grass-9);
 --colors-accent-emphasized: var(--colors-grass-10);
--colors-accent-text: var(--colors-grass-a11);
```
  
  Moreover, the ruby.default, ruby.emphasized and ruby.text token always have this syntax error:
  
```css
--colors-ruby-default: var(--colors-rugby-9);
--colors-ruby-emphasized: var(--colors-rugby-10);
--colors-ruby-text: var(--colors-rugby-a11);
```

It seems that there is a problem in the definition of this color in the code itself.

**Comment by cschroeter** [comment]
@adrbe 

Thanks for taking your time to create this issue. A fix is available in `0.26.1`
