### ISSUE TITLE
Docs completeness/consistency: Following setup guide should allow using examples without path adjustment

### ISSUE THREAD

**Issue by gabrielgrant** [cschroeter/park-ui#116]
Following the pandas + ark setup guides for a raw typescript/react/vite project, the installation/example snippets don't work without modification to the paths. Is there is some config combo/framework where these paths work out of the box?

It seems the `~/components` convention is more common in Nuxt? But even there, seems it still needs to be set up explicitly: https://nuxt.com/docs/guide/directory-structure/components#component-names

The instructions don't mention any path aliases, and results in `styled-system` dir in the project root. [Panda's getting started instructions take this into account by using `import { css } from '../styled-system/css';` in their initial example](https://panda-css.com/docs/installation/vite#start-using-panda) but Park assumes it can be imported directly as a package

Park should either:
1. Add to the [Getting started page](https://park-ui.com/docs/panda/overview/getting-started) to make mention of what config assumptions are made and/or what adjustments are needed to make imports work as written in the components' usage and installation snippets

or

2. change the snippets to be aligned with the result of the setup guide

eg in [code component](https://park-ui.com/docs/panda/components/code):

installation:
```
import { styled, type HTMLStyledProps } from 'styled-system/jsx'
import { code } from 'styled-system/recipes'
```

usage:
```
import { Code, type CodeProps } from '~/components/ui/code'
```

This seems to assume we're adding the component in `src/components/ui/code.tsx` (would have assumed `Code.tsx` would be more standard, but either way, this should be called out as an explicit recommendation/assumption)

Without further config, this means the component's imports need to be:
```
import { styled, type HTMLStyledProps } from '../../../styled-system/jsx'
import { code } from '../../../styled-system/recipes'
```

and the `~/components/ui/code` alias doesn't exist by default

I understand not wanting that path resolution in all the snippets. Perhaps include setup instructions (or assumptions to check -- maybe some frameworks set this up automatically?) so the nicer snippets work out of the box 

Seems these [tilde paths can be added to Vite/TS](https://medium.com/@davidmieloch/tilde-paths-with-eslint-typescript-and-webpack-971f694c9b15), so maybe recommend that? I generally think of `@` aliases as more common ([example](https://dev.to/tilly/aliasing-in-vite-w-typescript-1lfo)). Is there something I'm missing here? 

this seems to be the root issue with #57 

Happy to make some changes/additions to fix this, but want to understand the original intention of how this is supposed to be set up & work

**Comment by sholzmayer** [comment]
thanks for the hint. It might have changed over time, so I'll double check that it is up to date, also with the newly released CLI in mind.

**Comment by cschroeter** [comment]
@gabrielgrant 

Thanks for bringing this up. The quickstart projects should be a good starting point for everyone looking to use Park UI - however I think we can an should add to the docs a note about setting up paths in TypeScript.

Regarding the discussion about using `~` or `@` as an alias, I would like to express my preference for `~` for two main reasons:

1. In Unix-like environments, `~` represents the user's home folder, which parallels the concept of alias imports in a project. For instance, `import { Button } from '~/components/ui'` can be interpreted as _"From my project root, navigate to components -> ui and fetch the button."_ This metaphor aligns well with the intended functionality.

2. The `@` symbol is commonly used in npm packages, especially for organization packages like `@park-ui/cli`. This usage makes it challenging to differentiate between external and internal dependencies. Opting for `~` would reduce this ambiguity and enhance the clarity of our codebase.

**Comment by gabrielgrant** [comment]
Gotcha, thanks for the explanation!

those seem like very sensible reasons to prefer `~`. I have no particular attachment to `@`, just was thrown off because the `~` was unfamiliar, so wondered if I was missing something (like if this was a standard convention in one of the other supported frameworks). I know ideally the getting started section should be brief, but I'd have appreciated seeing a bit more explanation spelled out 

So to confirm before I submit a PR, your suggestion for how people should be setting this up is:

- install following existing directions
- set up a typescript alias for `~/` to src dir
- also set up an alias for `styled-system/` (in root dir)? or this be moved to `src/styled-system` so it can also be referenced from `~/`? or something else?

**Comment by cschroeter** [comment]
@gabrielgrant 

I think the bare minimum to get it to work is the following:

`tsconfig.json`

```json
"baseUrl": ".",
"paths": {
  "~/*": ["./src/*"]
}
```

For `vite` with your `vite.config.ts`

```ts
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
  plugins: [tsconfigPaths({ root: './' })],
})
```

With this folder structure:

```bash
.
├── src
├── styled-system
├── package.json
├── panda.config.ts
└── tsconfig.json
```

**Comment by gabrielgrant** [comment]
Awesome, thanks for spelling that out. Going to try it out now, and will do a docs PR 

To make sure I'm understanding: I think it's the `"baseUrl": "."` and `tsconfigPaths({ root: './' })`  that make the un-prefixed styled-system work, right? (`import { code } from 'styled-system/recipes'`)

**Comment by cschroeter** [comment]
Correct. The alias is only for components

**Comment by sholzmayer** [comment]
We could extend the CLI init command, that it adds the paths and baseUrl to the tsconfig.json as well.

**Comment by gabrielgrant** [comment]
@sholzmayer agree the CLI should probably also be mentioned in the Getting Started Guide. Not sure if it should be changing path aliases. Seems it supports setting these in `park-ui.json`, right? Maybe detect what the current actual aliases are (if any), and use those, instead of fixed defaults? And if there aren't any aliases set, offer to create them? Seems like this should probably be a separate issue, tho
