### ISSUE TITLE
Style Button link and Link component consistently? 

### ISSUE THREAD

**Issue by gabrielgrant** [cschroeter/park-ui#118]
Currently it seems `<Link>` has an underline on hover, while a `<Button>` styled as a link does not. Generally links should either in a different color or persistently underlined (or both, I suppose, but rare). Probably should call out a recommendation for how to best achieve this (custom styles? or should props be added to the components?)

**Comment by cschroeter** [comment]
@gabrielgrant

Thank you for taking the time to create this issue. 

I'm not satisfied with the current state of links within the Park Design System. First, we should not need a `link` variant for buttons. If you want to render a button that looks like a link, you can simply do:

```tsx
<Link asChild href="https://park-ui.com">
  <button>Park UI</button>
</Link>
```

From a UX perspective, I think a link should be, when rendered as part of a text, easily identifiable compared to the rest of the text. So using `accent.text` as a initial color and maybe something on hover. Not 100% sure. Lets see

**Comment by gabrielgrant** [comment]
Not sure if there's something I'm missing, but AFAICT this is still an issue, no?

**Comment by cschroeter** [comment]
@gabrielgrant 

For now you can simply do:

```jsx
  <Link asChild>
    <button type="button">Park UI</button>
  </Link>
  ```
  
  I have some cool new styles that will take care of that scenario
