### ISSUE TITLE
[Dialog] Missing TypeScript type definitions and appropriate usage

### ISSUE THREAD

**Issue by renchris** [cschroeter/park-ui#120]
### TypeScript errors

`'withProvider' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`

`'withContext' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`

`'Dialog' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`

`'DialogTrigger' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`

<img width="857" alt="image" src="https://github.com/cschroeter/park-ui/assets/57972348/c6125bb5-5adb-4d46-8ee6-8d85f2c563c7">

### Does not work with code example:

Dialog exports 

```ts
export {
  Backdrop,
  CloseTrigger,
  Content,
  Description,
  Dialog,
  DialogBackdrop,
  DialogCloseTrigger,
  DialogContent,
  DialogDescription,
  DialogPositioner,
  DialogTitle,
  DialogTrigger,
  Positioner,
  Root,
  Title,
  Trigger,
}
```

However code example does not match and uses the semantics of Dialog.component ie. Dialog.Backdrop instead

```ts
import { Portal } from '@ark-ui/react'
import { XIcon } from 'lucide-react'
import { Stack } from 'styled-system/jsx'
import { Button } from '~/components/ui/button'
import type { DialogProps } from '~/components/ui/dialog'
import * as Dialog from '~/components/ui/dialog'
import { IconButton } from '~/components/ui/icon-button'

export const Demo = (props: DialogProps) => {
  return (
    <Dialog.Root {...props}>
      <Dialog.Trigger asChild>
        <Button>Open Dialog</Button>
      </Dialog.Trigger>
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Stack gap="8" p="6">
              <Stack gap="1">
                <Dialog.Title>Dialog Title</Dialog.Title>
                <Dialog.Description>Dialog Description</Dialog.Description>
              </Stack>
              <Stack gap="3" direction="row" width="full">
                <Dialog.CloseTrigger asChild>
                  <Button variant="outline" width="full">
                    Cancel
                  </Button>
                </Dialog.CloseTrigger>
                <Button width="full">Confirm</Button>
              </Stack>
            </Stack>
            <Dialog.CloseTrigger asChild position="absolute" top="2" right="2">
              <IconButton aria-label="Close Dialog" variant="ghost" size="sm">
                <XIcon />
              </IconButton>
            </Dialog.CloseTrigger>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  )
}

```

**Comment by renchris** [comment]
I re-started my terminal, and my IDE, and restarted the application a few times, and it seems to work now. I'm not too sure why. Would anyone know how to properly set up the Park UI components to mitigate these types of definition and runtime issues?

**Comment by cschroeter** [comment]
@renchris 

Thanks for taking your time to create this issue. I'm not sure what caused this issue on your side in the first place but I'm happy that it works now.

If you have more of this type of issue please let me know.

**Comment by renchris** [comment]
Hi Christian. Thanks, I appreciate it.

The `2. Add Recipe` part says `This step is necessary only if you do not use any of the Park UI plugins.`

How do we use Park UI plugins?

I don't think it'll be the case but perhaps it's the recipe code that is slowing down or not syncing with the IDE and build? This issue only started to arise when I was trying to use and integrate Park UI components into my project. Let me know if there are any other metrics/info I can find to help identify/replicate the issue.
