### ISSUE TITLE
Combobox from docs doesn't work and throws error.

### ISSUE THREAD

**Issue by kaumac** [cschroeter/park-ui#122]
I tried using the installation instructions for the Combobox from the documentation page.

Using that I get an error saying that I need to wrap my page with `useComboboxContext`. But there's no documentation about this anywhere.

Then I used the combobox code from here and it worked:
`https://stackblitz.com/edit/github-e41h5b?file=src%2Fcomponents%2Fui%2Fcombobox.tsx,src%2Fapp%2Fpage.tsx,src%2Flib%2Fcreate-style-context.tsx,node_modules%2F%40ark-ui%2Freact%2Fcombobox%2Fcombobox.d.ts`

I tried doing a diff between the two but I can't really figure out what's different.

**Comment by kaumac** [comment]
PS: Sorry for creating so many issues lol, but hopefully it'll be helpful to other people that come across this

**Comment by kaumac** [comment]
Another thing I noticed is that the combobox "dropdown" area is not fixed with the input, instead it scrolls down with the window scroll. This might be an Ark issue?

https://github.com/cschroeter/park-ui/assets/1170740/70ea3250-7965-4f6f-8bce-158be010d33b

**Comment by cschroeter** [comment]
@kaumac 
I'm thankful for everyone that create "good" issues that helps me to improve Ark / Zag / Park UI . I will have a look shortly.

**Comment by kaumac** [comment]
> @kaumac I'm thankful for everyone that create "good" issues that helps me to improve Ark / Zag / Park UI . I will have a look shortly.

Thanks @cschroeter ! We all appreciate your hard work 😄

**Comment by cschroeter** [comment]
@kaumac 

I could not reproduce your issue with the combobox dropdown (see video)
Could you provide me a minimal repo that shows this errors? Stackblitz would be preferred :)

https://github.com/cschroeter/park-ui/assets/1846056/0e4e2dca-61b6-448d-8cab-7ff69182c89f

**Comment by cschroeter** [comment]
Closing this due inactivitiy. Feel free to create a new issue if needed.
