### ISSUE TITLE
Z-index Issue: Dropdowns Display Behind Dialog Overlay

### ISSUE THREAD

**Issue by BigDog1400** [cschroeter/park-ui#127]
In the existing preset file located at plugins/panda/src/theme/tokens/z-index.ts, there appears to be an issue with the z-index values assigned to the dropdown and dialog components. Currently, the z-index value for the dropdown component is lower than that of the dialog component.

This configuration results in an issue when a dropdown is placed within a dialog. When the dropdown is toggled, the items are displayed behind the dialog overlay, instead of being rendered on top as expected.

**Comment by calvo-jp** [comment]
Remembered encountering this issue and had to remove the portal for `combobox/select`

**Comment by cschroeter** [comment]
@BigDog1400,

Thank you for taking the time to create this issue. I've adapted this list from [Chakra](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/foundations/z-index.ts) on my positive experiences with it.

The problem you've described occurs when rendering a Select within a Dialog, which is obviously not correct.

The recommendation is to avoid using Portal unless necessary. You might be surprised at how often you can achieve the same results without using Portal, leading to cleaner code and fewer issues with z-index.

For further reading:

https://chakra-ui.com/community/recipes/z-index
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context

**Comment by BigDog1400** [comment]
I am away from my computer for testing it. But I guess that removing the Portal from the Select will solve this issue. If that's the case it may be worth to add an annotation in the documentation?

**Comment by cschroeter** [comment]
@BigDog1400 

I've updated to examples to not show a Portal component as there is no requirement to render them.

**Comment by BigDog1400** [comment]
Great 😃 Thanks 👍
