### ISSUE TITLE
[Table] There is a bug in the head

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#138]
There is a bug in the head

![image](https://github.com/cschroeter/park-ui/assets/53458125/da5f0ab5-19a1-4044-b3ec-a9ea530d6849)

**Comment by Omikorin** [comment]
Ahh, I wanted to issue same thing. I managed to get it right for one second.

![image](https://github.com/cschroeter/park-ui/assets/6079265/fe057552-5ba4-4577-938a-bc82f7453436)

![image](https://github.com/cschroeter/park-ui/assets/6079265/963802a4-17e2-4ae6-8d15-dafd8a3f251d)

There is some issue with hydration maybe
![image](https://github.com/cschroeter/park-ui/assets/6079265/4f0b5f7f-032d-48c9-aabe-a714b3f2fcdf)
