### ISSUE TITLE
CLI is not working for Vue

### ISSUE THREAD

**Issue by raymondmuller** [cschroeter/park-ui#155]
When running `npx @park-ui/cli init` and selecting the following options an error is thrown.

<img width="547" alt="Screenshot 2024-01-03 at 09 54 29" src="https://github.com/cschroeter/park-ui/assets/3808818/57368f86-13b6-4af9-8294-e85965adcc5a">

https://park-ui.com/registry/tailwind/vue/helpers/index.json seems to be missing

Same goes for https://park-ui.com/registry/tailwind/vue/components/index.json

**Comment by cschroeter** [comment]
@raymondmuller 

Thanks for taking your time to create this issue. I will have a look shortly

**Comment by raymondmuller** [comment]
@cschroeter anything I can do to help?

**Comment by Blinks44** [comment]
Maybe park-ui isn’t ready for Vue yet? I don’t see Vue components folder on github.

**Comment by cschroeter** [comment]
@dannylin108 this should be fixed by now

**Comment by dannylin108** [comment]
with @park-ui/cli version 0.5.0 still the same error. 

```
❯ pnpx @park-ui/cli add card
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
│
◇  Failed to download Card component
The "path" argument must be of type string. Received an instance of Array
```

**Comment by cschroeter** [comment]
Should work by now
