### ISSUE TITLE
feat(design): add kbd

### ISSUE THREAD

**Issue by Omikorin** [cschroeter/park-ui#158]
This has been requested at [Ark UI Roadmap](https://ark-ui.canny.io/feature-requests/p/keyboard-key-component-kbd).

A simple component to show a key or combination of keys - [Chakra UI example](https://chakra-ui.com/docs/components/kbd/usage)

**Comment by cschroeter** [comment]
Like https://park-ui.com/docs/panda/components/kbd ?

:-P

**Comment by Omikorin** [comment]
> Like https://park-ui.com/docs/panda/components/kbd ?
> 
> :-P

At night, I didn't think of going up from the components :D
