### ISSUE TITLE
Components break when using shorthand:false in config

### ISSUE THREAD

**Issue by chrber04** [cschroeter/park-ui#161]
I'm a huge fan of what you guys have done with Park UI, but I've run into a small issue. When shorthands:false is set in the Panda configuration, the components break since I assume that you have used shorthands for recipes. 

The apparent solution for me is to manually copy the recipes and substitute shorthand properties with their full-length versions. However, I believe integrating this approach within the library itself could be a potential improvement. That way, it doesn't matter whether shorthands is set to true or false, everything should still work smoothly

**Comment by cschroeter** [comment]
Mh can you provide me a small reproduction repo? I think this is a bug in Panda. If a preset uses shorthands or not should not affect your local config.

**Comment by cschroeter** [comment]
Closing this due inactivity. However using shorthand false on your end should not be an issue when a preset not use shorthands. So in that case please open an issue in the panda project.
