### ISSUE TITLE
[Bug?]: Assets are not optimized for astro + park-ui(panda/tailwind) + cloudflare

### ISSUE THREAD

**Issue by DrevaSergii** [cschroeter/park-ui#165]
I noticed a difference in the assets size after setting up Cloudflare deployment into your demo for astro with panda and tailwind.

Without Cloudflare the css file size is around 30Kb and with Cloudflare it is 190Kb.

Steps to reproduce:
1. Go to the official documentation, [getting-started](https://park-ui.com/docs/panda/overview/getting-started/) section.
2. Open astro template for panda / tailwind in stackblitz and download the source code.
3. Install dependecies, build and open preview by astro cli, check css file size (it should be ~30kb).
4. Add [cloudflare](https://docs.astro.build/en/guides/integrations-guide/cloudflare/) integration.
5. Build and open preview by wrangler cli, check css file size (it should be 190kb).

Or you can clone these repos:
[astro-panda-cloudflare](https://github.com/DrevaSergii/astro-panda-cloudflare)
[astro-tailwind-cloudflare](https://github.com/DrevaSergii/astro-tailwind-cloudflare)

<img width="1728" alt="Screenshot 2024-01-07 at 09 07 44" src="https://github.com/cschroeter/park-ui/assets/27158929/f2bcdad7-f97a-4bc8-b7d8-4acbe60215f0">
<img width="1728" alt="Screenshot 2024-01-07 at 09 08 00" src="https://github.com/cschroeter/park-ui/assets/27158929/94adfb6f-76b9-4ea0-bd11-08b575827842">

**Comment by cschroeter** [comment]
@DrevaSergii 

Thanks for taking your time to create this issue. I'm not sure why the Cloudflare Integration increases the CSS filesize by  –160kb but I guess this has something to do with not cleaning up unused CSS declarations.

For this project your reported issue is out of scope. I recommend you ask for help in the Astro or Panda / PostCSS Project.

Sorry for the inconvenience.
