### ISSUE TITLE
Typo in dependency name, on exports and imports of ui components.

### ISSUE THREAD

**Issue by RicardoGEsteves** [cschroeter/park-ui#166]
"@ark-ui/react": "1.2.1",
import { ark, type HTMLArkProps } from '@ark-ui/react'

shouldn't @park or is that on purpose?
just checking.

keep it up, awesome library. 💥🤞🙌

**Comment by cschroeter** [comment]
@RicardoGEsteves 

The idea for the name Park UI comes from [Ark UI](https://ark-ui.com) + Panda CSS. Therefore it is not a typo ;)
