### ISSUE TITLE
Slot Recipe Style Not Applying

### ISSUE THREAD

**Issue by renchris** [cschroeter/park-ui#169]
When I follow the steps of `Getting Started` and the `Table` component, the style from the `table.recipe.ts` file does not apply.

Here is a minimal re-production: https://github.com/renchris/panda-recipe-issue-reproduction

In the minimal reproduction, the style does not apply at all. In my original usage in my main repository, the style from the `styled-system` folder does apply, and the outputted table looks like the table in the example from the documentation, however, any modification made in the `table.recipe.ts` file does not get applied to the `styled-system` table file nor the outputted table component.

I have `pnpm install` for `panda codegen` and `pnpm dev` to run the attempted changes.

I am on NextJS App Router and the latest version of Panda CSS

**Comment by renchris** [comment]
Needed to import the recipe into the `panda.config.ts` as such

```ts
import table from 'recipes/table.recipe'
...
  theme: {
    extend: {
      slotRecipes: {
        table,
      },
    },
  },
...
```

and include just the fields I wish to change in the recipe in the `table.recipe.ts` file as such

```ts
import { defineSlotRecipe } from '@pandacss/dev'

const table = defineSlotRecipe({
  className: 'table',
  slots: ['root', 'body', 'cell', 'footer', 'head', 'header', 'row', 'caption'],
  jsx: ['ItemTable'],
  base: {
    cell: {
      verticalAlign: 'middle',
      backgroundColor: 'red',
    },
  },
})

export default table
```

**Comment by cschroeter** [comment]
@renchris 

Glad that you resolved the issue. I may want to update the docs to make it a bit more clear.
