### ISSUE TITLE
Allow all themes to be available

### ISSUE THREAD

**Issue by smontlouis** [cschroeter/park-ui#170]
I really like tamagui's approach, which allows themes to be used freely at a component level.
I think that, like tamagui, park-ui could have all the themes available at runtime, by modifying the conditions to accept accents.

This would make it easy to use any accent for a component.

conditions.ts
``` 
orange: ' &.orange, .orange &',
teal: ' &.teal, .teal &',
...


```

```
<html className="dark orange">
	<Text color="accent.default />
  	<Stack className="teal">
		<Text color="accent.default />
	</Stack>
</html>
```

**Comment by coopbri** [comment]
Have you seen Panda CSS [virtual color (color palettes)](https://panda-css.com/docs/concepts/virtual-color)? Would this cover your use case?

**Comment by cschroeter** [comment]
I think this is already possible for some components:

```tsx
<Button colorPalette="red" variant="solid">Button</Button>
  ```

Is this what you have in mind?

**Comment by smontlouis** [comment]
> Have you seen Panda CSS [virtual color (color palettes)](https://panda-css.com/docs/concepts/virtual-color) (which Park UI uses)? Would this cover your use case?

Yes I've seen it, but in my opinion, it creates redundancy, as it's necessary to recreate this for each component on which you need to apply a variety of accents, and even recreate the semantic tokens that already exist (I'm thinking in particular of accents / gray scales).

> I think this is already possible for some components:
> 
> ```js
> <Button colorPalette="red" variant="solid">Button</Button>
> ```
> 
> Is this what you have in mind?

In a way yes, it could create a redundancy with the colorPalette indeed.

I was thinking of using accents as colorModes (pink, orange, teal, etc) in multi-themes tokens
https://panda-css.com/docs/guides/multiple-themes

This is what I've done manually and it suits me well. 

I wanted to use accent tokens at all costs, without realizing that you had already defined tokens for each color. So instead I can simply use those tokens and define the colorPalette on my component.

```
<Stack colorPalette="teal">
    <Text color="colorPalette.default />
</Stack>
```

This is the way to go ?

Btw, I feel like your gray colors should be defined depending on the accent chosen (like radix-ui/colors). 
Was it deliberate not to push customization to that point?

I was expecting the gray palette, (hence the bg, fg, border palette) to depends on the accent chosen.
eg: red for accent color gives you a mauve palette for gray color.

![image](https://github.com/cschroeter/park-ui/assets/3509412/275d35dd-9877-4137-a594-c892831900bc)


Again, I come from Tamagui (which doesn't use colorScheme, but sub themes) so I might be a bit biased :)

**Comment by allysontsoares** [comment]
@cschroeter How can i enable the colorPalette on tailwind version? 
I'm trying to use the red example from the docs but it's not working, it stays black.


![image](https://github.com/cschroeter/park-ui/assets/110117326/ef7c5c53-24cf-4942-9f5a-f7ea846168e0)



> layout.tsx

```
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@park-ui/tailwind-plugin/preset.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

```

> GenericPageComponent
```
import Image from 'next/image'
import { Button } from '~/components/shared/button'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Button>Teste</Button>
      <div className="flex gap-4 items-center">
        <Button className="color-palette_red" variant="solid">
          Button
        </Button>
        <Button className="color-palette_red" variant="outline">
          Button
        </Button>
        <Button className="color-palette_red" variant="ghost">
          Button
        </Button>
      </div>
    </main>
  )
}

```

> tailwind.config.ts
```
import type { Config } from 'tailwindcss'
import  { parkwindPlugin } from '@park-ui/tailwind-plugin'

const config: Config = {
  plugins: [parkwindPlugin],
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['class'],
}
export default config

```

> package.json
```

{
  "name": "teste",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@ark-ui/react": "^1.2.1",
    "@park-ui/tailwind-plugin": "^0.16.0",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18",
    "tailwind-variants": "^0.1.20"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}

```

**Comment by caroguerrerosilvera** [comment]
@allysontsoares were you able to solve it in tailwind? I'm having the same problem, any ideas I can use temporarily to allow components to use the colorPalette?

**Comment by allysontsoares** [comment]
@caroguerrerosilvera I was unable to use ColorPalette, eventually I gave up and created buttonVariants like in Shadcn.  🫤

**Comment by caroguerrerosilvera** [comment]
@allysontsoares Got it. Thank you for taking the time to respond. I think I'll use a similar approach :(
