### ISSUE TITLE
How to update components?

### ISSUE THREAD

**Issue by adaboese** [cschroeter/park-ui#177]
I have initiated the project using:

```
pnpx @park-ui/cli add --all
```

park-ui has been updated since.

How do I update components to reflect the latest version?

Do I need to manually compare change log and patch differences?

**Comment by cschroeter** [comment]
@adaboese 

If everything is working, there is no urgent need to update the component snippets. Think of the snippets as a suggestion on how to get started rather than something that needs to be constantly updated.
