### ISSUE TITLE
[Tailwind] Add <alpha-value> to colors

### ISSUE THREAD

**Issue by leesiongchan** [cschroeter/park-ui#178]
https://github.com/cschroeter/park-ui/blob/e2ff6a2bc4f3c5a9311a0b0add12a998d2bc9b27/plugins/tailwind/src/plugin/preset.ts#L7

In the current tailwind plugin it sets the colors directly from a css variable (eg. hex), but this way we are losing the ability of setting opacity of the color/background. 

<img width="644" alt="image" src="https://github.com/cschroeter/park-ui/assets/324418/95d8b3d6-a663-41ef-a5ab-6be793271f33">

I can think of 3 solutions:
1. postcss plugin to convert hex to rgba like https://github.com/madeleineostoja/postcss-hexrgba
2. convert hex to rgb in js & create new list of css variables contain only the space-separated syntax?
3. use rgb in parkui & create a new list of css variables contain only the space-separated syntax?

**Comment by cschroeter** [comment]
@leesiongchan 

Thanks for taking your time to create this issue I will see what I can do.

**Comment by cschroeter** [comment]
With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
