### ISSUE TITLE
[Tooltip] Tooltip does not work on mobile

### ISSUE THREAD

**Issue by TreeOfLearning** [cschroeter/park-ui#179]
The tooltip does not show on (at least chrome ios) mobile devices.

To reproduce: 
- Visit [the tooltip demo](https://park-ui.com/docs/panda/components/tooltip) on a mobile device
- Press "Hover me" and notice that the tool tip never appears

**Comment by cschroeter** [comment]
How would you model hover in mobile? Iam not sure how to support that

**Comment by TreeOfLearning** [comment]
> How would you model hover in mobile? Iam not sure how to support that

For me it would be when the user taps on an element. In pure CSS I'd use `:focus` for this, so I guess you could do a media query to check if it's a mobile device and then use focus rather than hover.

**Comment by TreeOfLearning** [comment]
> But tap would be the equivalent to click on mobile, right? So what about a tooltip that wraps a button - what should happen here?

I suppose they are similar, yes. For non-clickable objects, `:focus` or `:active` would work just fine. I'd make the argument that something clickable like a button shouldn't be wrapped by a tooltip, at least on mobile; instead you would have a separate element for the tooltip. Wrapping the button itself is poor UX because of the very issue that you can't activate the tooltip without clicking. As a mobile user you wouldn't expect a tooltip to activate on a button. So I don't think that's an issue.
