### ISSUE TITLE
Add: Aspect Ratio Component To display content within a desired ratio.

### ISSUE THREAD

**Issue by Qodestackr** [cschroeter/park-ui#184]
Ready to Implement and Hold a Discussion in this issue. Let me know what features are pending and so on. @cschroeter Great work and already using some features in this site https://jhub-self.vercel.app/!

**Comment by cschroeter** [comment]
@Qodestackr 

Thanks for taking your time to create this issue. I'm not exactly sure but I assume you asking for an Aspect Ratio component.

```jsx
 <Box aspectRatio="4/3">Preview</Box>
 ```
 
 Does this solve your issue?

**Comment by Qodestackr** [comment]
Ah nice! 💯

**Comment by Qodestackr** [comment]
We can close this. Kindly expose ongoing tasks in Project tab
