### ISSUE TITLE
(Question) Best way to add error/invalid states to inputs? 

### ISSUE THREAD

**Issue by TreeOfLearning** [cschroeter/park-ui#185]
Sorry, this isn't an issue with the library, rather me displaying my ignorance! I noticed some of the ark-ui base components accept an `invalid: boolean` prop (from the docs: `"Whether the input's value is invalid."`). I'm not sure what the best way is to actually use this prop visually; it would be nice to give inputs a red border or something if it is invalid. But - and I feel like an idiot for saying this - I have no idea how I would go about adding that to, for example, the `Input` component:

```
export const Input = styled(ark.input, input)
export interface InputProps extends ComponentProps<typeof Input> {}
```

Any ideas?

Thanks!

**Comment by cschroeter** [comment]
@TreeOfLearning 

This is actually pretty easy you can simply extend the input recipe by adding an invalid prop like shown below:

```ts


import { defineConfig } from '@pandacss/dev'

export default defineConfig({
  // ...
  theme: {
    extend: {
      recipes: {
        input: {
          base: {
            _invalid: {
              borderColor: 'red.9',
              boxShadow: '0 0 0 1px var(--colors-color-red-9)',
            }
          },
        },
      },
    },
  },
})
```

I could hardcode this to red or introduce a semantic token for invalid / error colors. Thats the reason why its not there

**Comment by TreeOfLearning** [comment]
@cschroeter 
Thanks, that's a really simple solution. I've just tried it though, and after adding that to the panda config (then running codegen etc.), when I then try to use the invalid prop I get the following error, and no invalid style is shown:

```
Warning: Received `true` for a non-boolean attribute `invalid`.
```

I'm using it like this:

```
<Input placeholder="10" invalid />
```

I'm certain I'm doing something foolish here! Very new to the whole pandacss/(p)arkui thing - sorry!

**Comment by cschroeter** [comment]
I think there is no way to manually set an Input to `invalid` You maybe can try `aria-invalid`
The idea is that you provide the invalid styles `_invalid: { }` and if you have for example an input like shown below and you start adding uppercase letters, the input turns invalid showing you your error message.

```jsx
<input name="secret" type="text" value="test" pattern="[a-z]+" /> />
```
