### ISSUE TITLE
SegmentGroupIndicator is on top of the item

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#191]
![image](https://github.com/cschroeter/park-ui/assets/53458125/0656d29e-4a7d-42e7-ba1f-43d5f7270fe7)

**Comment by kovsu** [comment]
It's caused by zag.js I think.
![image](https://github.com/cschroeter/park-ui/assets/82451257/bf173589-0122-4985-b731-feea2329e776)
