### ISSUE TITLE
bug: many miscellaneous typescript errors

### ISSUE THREAD

**Issue by jlarmstrongiv** [cschroeter/park-ui#193]
When using the `npx @park-ui/cli`, the `styled.tsx` file is never created

In `avatar.tsx`, 
- `'ref' is declared but its value is never read.ts(6133)`.

In `badge.tsx`, 
- missing import for `type HTMLArkProps`
- mismatch between `HTMLArkProps<'button'>` and `ark.div`

In `button.tsx`,
- missing import for `type HTMLArkProps`

In `code.tsx`,
- missing import for `type HTMLArkProps`

In `form-label.tsx`,
- missing import for `type HTMLArkProps`
- mismatch between `HTMLArkProps<'button'>` and `ark.label`

In `icon-button.tsx`,
- missing import for `type HTMLArkProps`

In `input.tsx`,
- missing import for `type HTMLArkProps`
- mismatch between `HTMLArkProps<'button'>` and `ark.input`

In `kbd.tsx`,
- missing import for `type HTMLArkProps`
- not an error, but still a mismatch between `HTMLArkProps<'button'>` and `ark.kbd`

In `link.tsx`,
- missing import for `type HTMLArkProps`
- mismatch between `HTMLArkProps<'button'>` and `ark.a`

In `menu.tsx` (see ark [changelogs](https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/CHANGELOG.md))
- `Property 'Indicator' does not exist on type '((props: MenuProps) => Element) & { Root: (props: MenuProps) => Element; Arrow: ForwardRefExoticComponent<MenuArrowProps & RefAttributes<HTMLDivElement>>; ... 10 more ...; TriggerItem: ForwardRefExoticComponent<...>; }'. `
- `Property 'OptionItemIndicator' does not exist on type '((props: MenuProps) => Element) & { Root: (props: MenuProps) => Element; Arrow: ForwardRefExoticComponent<MenuArrowProps & RefAttributes<HTMLDivElement>>; ... 10 more ...; TriggerItem: ForwardRefExoticComponent<...>; }'. `
- `Property 'OptionItemText' does not exist on type '((props: MenuProps) => Element) & { Root: (props: MenuProps) => Element; Arrow: ForwardRefExoticComponent<MenuArrowProps & RefAttributes<HTMLDivElement>>; ... 10 more ...; TriggerItem: ForwardRefExoticComponent<...>; }'. Did you mean 'OptionItem'? `

In `pagination.tsx`, 
- my custom import syntax specialized in the cli as `@park/components` is not respected, resulting in broken `~/components/ui/button` and `~/components/ui/icon-button` imports

In `pin-input.tsx`, 
- my custom import syntax specialized in the cli as `@park/components` is not respected, resulting in broken `~/components/ui/input` import
- `Type '"md" | "sm" | "lg" | "xl" | "2xl" | "xs" | undefined' is not assignable to type 'undefined'.
  Type '"md"' is not assignable to type 'undefined'. ` (the InputVariantProps may be overridden by the [HTML attribute `size`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size))

In `skeleton.tsx`, 
- `Type '{ children?: ReactNode; className?: string | undefined; slot?: string | undefined; style?: CSSProperties | undefined; title?: string | undefined; key?: Key | null | undefined; ... 262 more ...; ref: ForwardedRef<...>; }' is not assignable to type 'IntrinsicAttributes & Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & { ...; } & { ...; }'.
  Property 'animation' does not exist on type 'IntrinsicAttributes & Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & { ...; } & { ...; }'.ts(2322)`

In `slider.tsx`
- `'ref' is declared but its value is never read.ts(6133)`.

In `textarea.tsx`
- missing import for `type HTMLArkProps`
- mismatch between `HTMLArkProps<'button'>` and `ark.textarea`

I was able to fix most of these locally, except for `menu.tsx`, `pin-input.tsx`, and `skeleton.tsx`

**Comment by cschroeter** [comment]
@jlarmstrongiv 

Thanks for taking your time. I've updated the components accordingly.
