### ISSUE TITLE
bug: missing "./preset.css" specifier in "@park-ui/tailwind-plugin" package

### ISSUE THREAD

**Issue by jlarmstrongiv** [cschroeter/park-ui#194]
The exports in the package.json is missing `./preset.css`

```
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./package.json": "./package.json"
  }
```

**Comment by oferitz** [comment]
Seeing the same

**Comment by jlarmstrongiv** [comment]
A PR would be the best solution, if you’re up for it @oferitz 😄

In the meantime, you can add `"./preset.css": "./preset.css"` in your `node_modules` and run `npx patch-package @park-ui/tailwind-plugin --exclude 'nothing'`

**Comment by oferitz** [comment]
@jlarmstrongiv Thanks 👍
