### ISSUE TITLE
bug: doesn’t play nicely with tailwindcss preflight styles

### ISSUE THREAD

**Issue by jlarmstrongiv** [cschroeter/park-ui#195]
It appears that park-ui styling conflicts with and is overridden by the default tailwindcss preflight.  

For example, the pin input component in the docs 

<img width="207" alt="image" src="https://github.com/cschroeter/park-ui/assets/20903247/4e601e57-9f12-4b6b-901e-3523b5224aee">

vs the pin component with the default tailwindcss preflight

<img width="210" alt="image" src="https://github.com/cschroeter/park-ui/assets/20903247/048ab0a3-2e63-45ad-bb67-25ded99e2bd7">

This is very disappointing for me, since I was hoping to drop in park-ui and slowly migrate to it, without destroying my site styles or park-ui styles.

Ideally, park ui would depend on normal tailwindcss and its arbitrary variants, not injecting it’s own custom base css that conflicts with everything else.

Unfortunately, it looks like I’ll have to give up on park-ui

**Comment by cschroeter** [comment]
@jlarmstrongiv 

Thanks for bringing this up. I've checked and I'm happy to report that this should work now just fine. I will file a new release shortly.

https://github.com/cschroeter/park-ui/assets/1846056/cb70c8ec-6faf-4fef-bf15-63fd29107f74

**Comment by jlarmstrongiv** [comment]
Hey @cschroeter I just wanted to say thank you! Your fixes for `park-ui` have encouraged me to try it again—and everything looks great!  Can’t wait to give it a test run

<img width="196" alt="image" src="https://github.com/cschroeter/park-ui/assets/20903247/49fd6ce4-4bfa-428a-8c59-1ee4c5fc8ef1">
