### ISSUE TITLE
Bug: Discrepancy in Tags-Input Component Behavior Between Park-UI and Ark-UI

### ISSUE THREAD

**Issue by BigDog1400** [cschroeter/park-ui#200]
Hello,

During my exploration of the Tags-Input component (https://park-ui.com/docs/panda/components/tags-input), I noticed an inconsistency compared to its implementation in Ark-UI (https://ark-ui.com/docs/components/tags-input).

Specifically, when an element is double-clicked to update it, the said element disappears rather than permitting the intended update. This behavior is different from what is observed on the Ark-UI site.

**Comment by cschroeter** [comment]
@BigDog1400 

Thanks for taking your time to create this issue. There is an issue for the `TagsInput` that is already solved in Ark and will be released. Ark ui React and Solid 2.0 are pretty much ready to go. Please expect a fix in the next release
