### ISSUE TITLE
Some strange behaviours of <Menu /> for solid js

### ISSUE THREAD

**Issue by arch-mage** [cschroeter/park-ui#204]
I found some strange behaviours of `<Menu />` for solid js:

 1. Menu does not appear in the expected place. Somehow it appear in the top
    left corner of the page when menu is closed by clicking outside of menu
    item. If I close the menu by clicking any menu item, the menu will appear
    in the right place.
 2. The button that triggers the menu to open, somehow accumulates it's classes.
 3. Some data attributes in the rendered button is sometimes disappear and
    reappear. It's related to the positioning of the menu. Because, when those
    data attributes are gone, the menu will appear in the top corner.

Here's the reproducible code https://github.com/arch-mage/park-ui-menu-bug

**Comment by cschroeter** [comment]
This should be fixed with 2.0. We ran into an issue with asChild.

**Comment by cschroeter** [comment]
I tried this with Ark UI Solid 2.0.1 and it works.
