### ISSUE TITLE
BUG: tooltip loses closed animation

### ISSUE THREAD

**Issue by kovsu** [cschroeter/park-ui#205]
| Current behaviour | Expect behaviour |
|--------|--------|
|<video src="https://github.com/cschroeter/park-ui/assets/82451257/4d7473c4-e348-416e-b4fc-d736dc3d282d" /> |<video src="https://github.com/cschroeter/park-ui/assets/82451257/63a88238-4795-4022-ac7d-656e5e524005" /> |

# Problem

1. After tooltip initialization, the inline style of `Tooltip.positioner` will have the property `transform: translate3d(0, -100vh, 0)`.
2. When I hover over `Tooltip.trigger`, the inline style of `Tooltip.positioner` will change to the following: 
```css
transform: translate3d(0px, var(--x), var(--y);
--x: 232.5px;
--y: 143px;
...
```
3. When I move the mouse away, the transform property will revert to `translate3d(0, -100vh, 0)`, but what we desire is for it to remain unchanged, still being `translate3d(0px, var(--x), var(--y))`.

# Current Solution

 I don't think this is a brilliant solution. @cschroeter Can you give me advices?

<img width="732" alt="截屏2024-01-30 16 28 48" src="https://github.com/cschroeter/park-ui/assets/82451257/766e63eb-39ac-4ec1-9782-e1017f70df0a">

**Comment by cschroeter** [comment]
This is fixed in ark 2.0 and resolved in a few hours :)

**Comment by kovsu** [comment]
@cschroeter Can you show me which commit in ark-ui that repaired it? 😀

**Comment by cschroeter** [comment]
@kovsu 

Sure - here you go https://github.com/chakra-ui/zag/commit/e0374847390a88e69d6e4b33f42fc6ab6291b2a8
