### ISSUE TITLE
styled-system/jsx and styled-system/recipes directories are not created

### ISSUE THREAD

**Issue by npetridis** [cschroeter/park-ui#218]
I made a fresh next.js with typescript project
Installed Panda css as instructed by park UI docs
Followed the rest of the park UI steps and setup
When I run the code I get the error
```
⨯ ./src/components/Button.tsx:2:0
Module not found: Can't resolve 'styled-system/jsx'
  1 | import { ark } from '@ark-ui/react'
> 2 | import { styled, type HTMLStyledProps } from 'styled-system/jsx'
  3 | import { button } from 'styled-system/recipes'
  4 |
  5 | export const Button = styled(ark.button, button)
  ```
You can see at the screenshot that no /jsx or /recipes directories exist under styled-system directory
and I also try absolute and relative imports in the opened file at the editor
![Screenshot 2024-02-05 at 02 06 29](https://github.com/cschroeter/park-ui/assets/6136507/6b089061-dadb-4e05-a568-1e84fa0ed137)

**Comment by cschroeter** [comment]
@npetridis 
Thanks for taking your time to report this issue. I think you missed this step:

<img width="804" alt="image" src="https://github.com/cschroeter/park-ui/assets/1846056/e55aa669-42f7-4e1b-92e6-b991948932fe">
