### ISSUE TITLE
feat(examples): add solid start example

### ISSUE THREAD

**Issue by pixelmord** [cschroeter/park-ui#22]
Hi,

I am a seasoned React and Typescript developer and I'm currently exploring SolidJS and PandaCSS as an alternative to React w Tailwind.

I created a monorepo to try out various things, see the start of an implementation for solid components here: 
https://github.com/pixelmord/nextstack/tree/main/apps/rocksolid/src/components/ui

So if you want help creating an example with solidJS for this project, I could open a PR if you haven't started sth yourself?

And depending on you plans for the docs I could contribute there as well

What Do you think?

**Comment by pixelmord** [comment]
A created a draft PR @cschroeter 

I reached out to you on twitter, but no DM possible, but you can go to my website and find my contact details 
https://composableweb.com/resume/en

**Comment by cschroeter** [comment]
@pixelmord 

A simple but working Solid Start version is now available https://stackblitz.com/github/cschroeter/park-ui/tree/main/examples/panda/solid/solid-start?file=README.md
