### ISSUE TITLE
Select "'set' on proxy: trap returned truish for property 'items' which exists in the proxy target as a non-configurable and non-writable accessor property without a setter"

### ISSUE THREAD

**Issue by philipbalbas** [cschroeter/park-ui#222]
![start-screenshot](https://github.com/cschroeter/park-ui/assets/14971706/bd9a8c17-31f5-4580-b8bc-f2e78ffed15c)

Park Select component keeps running to this error. Base Ark Select component works just fine.
I'm using the following versions:
```
  "@ark-ui/solid": "^2.0.1",
  "@park-ui/tailwind-plugin": "^0.19.1",
  ```

**Comment by philipbalbas** [comment]
@cschroeter here you go
https://codesandbox.io/p/github/philipbalbas/upgrade/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsai0wtr0006356etckb2cju%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsai0wtr0002356edjt4jdvt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsai0wtr0004356ehtihwoyb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsai0wtr0005356epwwcddxz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsai0wtr0002356edjt4jdvt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsai0wtq0001356ekpm59g5f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsai0wtr0002356edjt4jdvt%2522%252C%2522activeTabId%2522%253A%2522clsai0wtq0001356ekpm59g5f%2522%257D%252C%2522clsai0wtr0005356epwwcddxz%2522%253A%257B%2522id%2522%253A%2522clsai0wtr0005356epwwcddxz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsaift7900kp356ek7gl0c0h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsaift7900kp356ek7gl0c0h%2522%257D%252C%2522clsai0wtr0004356ehtihwoyb%2522%253A%257B%2522id%2522%253A%2522clsai0wtr0004356ehtihwoyb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsai0wtr0003356enxtekzjd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsaibo2o0023dlhq26xi9pxh%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsai0wtr0003356enxtekzjd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by cschroeter** [comment]
Closing this in favour of https://github.com/chakra-ui/ark/issues/2151
