### ISSUE TITLE
[docs] Getting started instructions missing cli tool instructions 

### ISSUE THREAD

**Issue by aryzing** [cschroeter/park-ui#236]
After going through the "Getting Started" section, when copying a component's code, there are often errors related to `~/lib` and `~/components` imports. Seems the steps on this page are missing the cli setup.

Also, earlier today there was a CLI section on the docs that seems to have disappeared, guess these parts of the docs are being actively worked on?

**Comment by cschroeter** [comment]
@aryzing 

Thanks for taking your time to create this issue. I agree that the docs at this point could be a bit more precise.
How ever the step you are missing is part of the `getting-started.mdx` so I think we can just merge them.

<img width="841" alt="image" src="https://github.com/cschroeter/park-ui/assets/1846056/93846e4b-bee5-4432-a0c6-108b4feceb8f">

**Comment by aryzing** [comment]
Sure, seems like merging Setup + CLI into one would make sense

**Comment by cschroeter** [comment]
The Getting Started page has been revised.
