### ISSUE TITLE
Bug: Missing {colors.white} token.

### ISSUE THREAD

**Issue by kaumac** [cschroeter/park-ui#243]
I'm updating park-ui on my project and it hasn't been very smooth.
I got a lot of missing color token errors, which I fixed by replacing:
```
presets: ['@park-ui/panda-preset', '@pandacss/preset-base'],
  ```
  with 
  ```
  presets: [
    '@pandacss/preset-base',
    createPreset({
      additionalColors: ['*']
    })
  ],
  ```
  on my panda config file.
  
  Now I'm getting errors about a missing `{colors.white}` token. I then tried using `{white}` as per the release notes of `0.35.1` but then I get errors about token `white` not existing.
  
  Btw, perhaps breaking changes (like having to add `additionalColors` could be clearly flagged on the release notes, that'd be super helpful)

**Comment by kaumac** [comment]
This is how I'm using the white token on my theme:
```
accent: {
        default: { value: { base: '{colors.lavender.9}', _dark: '{colors.lavender.1}' } },
        emphasized: { value: { base: '{colors.lavender.9}', _dark: '{colors.lavender.2}' } },
        fg: { value: { base: '{colors.white}', _dark: '{colors.white}' } }
      },
```

**Comment by cschroeter** [comment]
@kaumac 

There is an issue with the validation logic in Panda. I declare `black` and `white` as follows:

```jsx
defineTokens.colors({
  black: {
    DEFAULT: { value: '#000000' }, // <- here {colors.black} is declared but the validation logic ignores this
    a1: { value: 'rgba(0, 0, 0, 0.05)' },
    // ..
    a12: { value: 'rgba(0, 0, 0, 0.95)' },
  },
  ```
  
  So a quick fix for now is just to use `black` and `white` like so:
  ```jsx
    fg: { value: { base: 'white', _dark: 'white' } }
    // should also work
    fg: { value: "white" }
```
