### ISSUE TITLE
[docs] Inconsistent documentation

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [cschroeter/park-ui#247]
Hello! I'm trying to use Park UI in a brand new Next.js project. However, the Getting Started documentation is missing some crucial information (the whole doc, to be honest).

I'm not sure exactly where. What I can say is that if you follow the guide to the letter without performing any additional steps, you won't have a working UI library. There are too many errors related to imports and missing packages, especially **styled-components** related stuff.

I really liked this UI; however, the docs need some improvement. They can be really challenging for beginners.

Thanks a lot, I hope to have a improved version of this in the future to use on new projects. 👍

**Comment by cschroeter** [comment]
@BRGustavoRibeiro 

Thanks for taking your time to report the issue. I just created a new Next.js project with Panda CSS and could get a working project in less then 3 minutes. However I noticed that the `"baseUrl": "."` is something crucial to add to your `tsconfig.json`

I will update the docs to include this step.

Besides I could not spot any major flaws. Happy to learn the parts where you struggled.

**Comment by BRGustavoRibeiro** [comment]
I already started the project with another UI lib, but I'm willing to try this one more time.

Give me a few hours - I'll try to perform the install and thoroughly document my journey. I'll keep you updated through this issue.

**Comment by BRGustavoRibeiro** [comment]
@cschroeter Somehow I misread the docs and I managed to follow the Panda Getting Started instructions instead of the Tailwind one. 

I managed to successfully install ParkUI on my project! 😎 I only had to install _tailwind-variants_ which was missing. It might be good to update the docs to add this info as it doesn't install it automatically.

Thanks for the help!
