### ISSUE TITLE
bug: calendar demo selecting range when only a single date is expected

### ISSUE THREAD

**Issue by jlarmstrongiv** [cschroeter/park-ui#248]
https://github.com/cschroeter/park-ui/assets/20903247/218b42b8-fbba-42db-9e05-d5e1e2d43e3a

**Comment by cschroeter** [comment]
@jlarmstrongiv 

Thanks for taking your time to report this issue. The demo has been updated to use two input fields

**Comment by jlarmstrongiv** [comment]
@cschroeter is there an example that is a single date field without a range too?

**Comment by cschroeter** [comment]
Just change the mode and use one input

<img width="1642" alt="image" src="https://github.com/cschroeter/park-ui/assets/1846056/353230f5-1036-49b6-a46a-9049a1bbebf3">
