### ISSUE TITLE
Select disabled state - consider styling the trigger as disabled when the control is disabled

### ISSUE THREAD

**Issue by wontondon** [cschroeter/park-ui#257]
The select component supports the disabled state, but when disabled the control still looks active. The control can't be clicked and the states are all working correctly. It just looks like the control is still active. Ideally the control would look disabled when disabled.

Disabled Park UI select
<img width="465" alt="Screenshot 2024-03-05 at 12 51 25 PM" src="https://github.com/cschroeter/park-ui/assets/374289/fccac6e7-5c47-44de-91ec-2e6e467dbf8a">

Standard disabled html select
<img width="186" alt="Screenshot 2024-03-05 at 12 29 58 PM" src="https://github.com/cschroeter/park-ui/assets/374289/5a132875-42a3-499b-b4f6-137fd9e1fd66">

**Comment by cschroeter** [comment]
@wontondon 

Thanks for taking your time and creating the PR.
