### ISSUE TITLE
Native elements attributes are obfuscated?

### ISSUE THREAD

**Issue by binajmen** [cschroeter/park-ui#259]
If I take for example the `Button` component:
```ts
import { ark } from "@ark-ui/solid";
import type { ComponentProps } from "solid-js";
import { styled } from "styled-system/jsx";
import { button } from "styled-system/recipes";

export const Button = styled(ark.button, button);
export interface ButtonProps extends ComponentProps<typeof Button> {}
```

The native attributes such as `type` or `form` of the underlying `<button>` are not defined in the resulting props:

![Screenshot 2024-03-06 at 15 40 04](https://github.com/cschroeter/park-ui/assets/15611419/18f9f9dd-ead5-4858-96fb-0c22a2c9bd88)

In fact, I can even define something erroneous with no errors/warnings:
```ts
<Button typeEEEee="button" ...>
        ^^^^^^^^^
        (property) typeEEEee: string
```

**Comment by cschroeter** [comment]
@binajmen 

Thanks for taking your time to report this issue. There is an open [issue](https://github.com/chakra-ui/ark/issues/2151). Please replace `ark.button` with `button` for now.
