### ISSUE TITLE
Combobox (panda-css) is missing recipe for 'clearTrigger' slot

### ISSUE THREAD

**Issue by dannylin108** [cschroeter/park-ui#263]
I'm using park-ui's `createPreset` like this:

```
import { defineConfig } from '@pandacss/dev'
import { createPreset } from '@park-ui/panda-preset'

export default defineConfig({
  preflight: true,
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'teal',
      grayColor: 'sage',
      borderRadius: '2xl',
    }),
  ],
  include: ['./src/**/*.{js,jsx,ts,tsx,astro}'],
  jsxFramework: 'solid',
  outdir: 'styled-system'
})
```

Is that enough to have all needed recipes available?

But even if use `defineSlotRecipe` for `<Combobox/>` component (https://park-ui.com/docs/panda/components/combobox), it misses  slot `clearTrigger`.

BTW, is it possible to tweak park-ui's slot recipes by adjusting or adding only what is necessary?

**Comment by astahmer** [comment]
yes you can adjust the recipe however you want using [the extend keyword](https://panda-css.com/docs/concepts/extend) or by [omitting parts of it](https://panda-css.com/docs/concepts/hooks#tweak-the-config)

**Comment by cschroeter** [comment]
@dannylin108 

This should be fixed by now. Thanks @astahmer for pointing to this workaround.
