### ISSUE TITLE
New @pandacss/dev version breaks default styles

### ISSUE THREAD

**Issue by alanhoff** [cschroeter/park-ui#264]
I'm not entirely sure what happened, but `@pandacss/dev@0.34.2` (and newer versions) is breaking the default styles for some components, here's the before/after comparison:

### Before 

![image](https://github.com/cschroeter/park-ui/assets/1044223/3c564354-bcb5-4632-990c-bef86a20b770)

### After

![image](https://github.com/cschroeter/park-ui/assets/1044223/ad1279a9-49b7-41b8-9384-f4be9ab078b7)

And here's a repository demonstrating the bug:

https://stackblitz.com/edit/github-wy3n6n

**Comment by JericoFX** [comment]
all radio groups are broken too 
![image](https://github.com/cschroeter/park-ui/assets/56100605/e811e853-8e34-4254-9df0-010ccdc2deb5)

**Comment by cschroeter** [comment]
@alanhoff @JericoFX  

Thanks for taking your time to report this issue. A fix will be available in the next Panda release.
