### ISSUE TITLE
bug: doesn’t play nicely with tailwindcss preflight styles

### ISSUE THREAD

**Issue by jlarmstrongiv** [cschroeter/park-ui#265]
Adding park-ui has broken my existing TailwindCSS components, since it alters the preflight styles.

A default focused form field looks like:

<img width="228" alt="image" src="https://github.com/cschroeter/park-ui/assets/20903247/e38573de-7bdc-47e8-bcf2-b3e959b6eac0">

While park-ui changes the styles to:

<img width="253" alt="image" src="https://github.com/cschroeter/park-ui/assets/20903247/4b55f537-bbb9-459a-8d4d-8d4e0060b37a">

More focusing on the size and outline radius of the form field, the fonts are different and that’s due to testing.

Related to https://github.com/cschroeter/park-ui/issues/195 this time, instead of park-ui’s styles breaking, my existing styles are breaking.  

```
"@park-ui/tailwind-plugin": "0.20.1",
```

**Comment by cschroeter** [comment]
With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
