### ISSUE TITLE
Typescript complains of css typings JsxStyleProps

### ISSUE THREAD

**Issue by tzarger** [cschroeter/park-ui#271]
Hello @cschroeter , I started with a new project and imported all components and several of them do this:

`const [cssProps, localProps] = splitCssProps(avatarProps)`

and then in the component, this as an example calls `css(cssProps)` and Typescript is not happy.

`<ArkAvatar.Root ref={ref} className={cx(styles.root, css(cssProps), className)} {...rootProps}>`

Here you can see the Typescript error.

![CleanShot 2024-03-16 at 17 20 47@2x](https://github.com/cschroeter/park-ui/assets/1757589/5f3d986c-badd-4813-ab42-6ad28d36ded3)

Should the `css()` function be updated to accept JsxStypeProps as well?

**Comment by astahmer** [comment]
should be fixed
https://github.com/chakra-ui/panda/pull/2383

**Comment by cschroeter** [comment]
@tzarger 

Thanks for taking your time. I've updated the places. Looks good :)
