### ISSUE TITLE
[Tooltip] Issue

### ISSUE THREAD

**Issue by kaiqueaguilar** [cschroeter/park-ui#275]
Expected behavior:
![image](https://github.com/cschroeter/park-ui/assets/92055543/7f4f3443-75a0-4599-b12b-d2f171a9da78)

Current behavior:
![image](https://github.com/cschroeter/park-ui/assets/92055543/e1f489de-d779-4f74-96d3-b4a27d00e2cb)

**Comment by cschroeter** [comment]
@kaiqueaguilar

Thanks for taking your time to report this issue. This will be fixed with a next Panda release https://github.com/cschroeter/park-ui/issues/264
