### ISSUE TITLE
[panda + solid] Some components do not have proper type.

### ISSUE THREAD

**Issue by noriapi** [cschroeter/park-ui#282]
In panda/solid, some components do not have proper type.

For example, the [Button](https://github.com/cschroeter/park-ui/blob/main/components/panda/solid/src/components/ui/button.tsx) component props have `any` type.

![solid](https://github.com/cschroeter/park-ui/assets/70106808/f1908195-bc02-4d64-a6f6-01a62f70f2e3)

But in react, the [Button](https://github.com/cschroeter/park-ui/blob/main/components/panda/react/src/components/ui/button.tsx) component type looks like this.

![react](https://github.com/cschroeter/park-ui/assets/70106808/ab26e2ae-259b-4965-89b7-94f1780d2220)

So type checkings do not work when using these componets.

**Comment by cschroeter** [comment]
@noriapi 

Thanks for taking your time to report this issue. A fix will be available in Ark v3 https://github.com/chakra-ui/ark/issues/2151
