### ISSUE TITLE
When selecting any text, the first letter becomes blue

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#286]
I think this is a problem with the new Panda css version

![image](https://github.com/cschroeter/park-ui/assets/53458125/1867566a-5548-4921-bdf0-7c5137dd843d)

**Comment by cschroeter** [comment]
@juliomuhlbauer I'm not sure if this a bug or a feature :D

**Comment by juliomuhlbauer** [comment]
A feature for sure 😂

**Comment by juliomuhlbauer** [comment]
Updating to the new Panda css version solves the issue
