### ISSUE TITLE
asChild is not correct with SolidJS

### ISSUE THREAD

**Issue by dannylin108** [cschroeter/park-ui#287]
This code with SolidJS framework renders `<button>` inside `<button>` 

```jsx
<Menu.Trigger asChild>
    <Button variant="outline">
          Open Menu
     </Button>
</Menu.Trigger>
```

But with React it renders single `<button>` (at least park-ui website's example does).

The same problem with `<Dialog.CloseTrigger>`

**Comment by cschroeter** [comment]
@dannylin108 

Thanks for taking your time to report this issue. This will change with [Solid v3.0 ](https://github.com/chakra-ui/ark/issues/2331)

The current approach in Ark is not sufficient for this type of problem.
