### ISSUE TITLE
CLI does not respect path aliases for components in import statements

### ISSUE THREAD

**Issue by yu7400ki** [cschroeter/park-ui#288]
CLI currently respects path aliases for 'utils' in import statements, but does not respect path aliases for 'components'.

https://github.com/cschroeter/park-ui/blob/ef434b99e8a0a03b12b1efeb85f01187b33d5726/cli/src/commands/add.ts#L24-L32

**Comment by cschroeter** [comment]
@yu7400ki 

This has been fixed in `0.7.0`.
