### ISSUE TITLE
ToggleButton works incorrectly on touch devices

### ISSUE THREAD

**Issue by dannylin108** [cschroeter/park-ui#289]
Even on the park-ui website, on a touch device (real phone or chrome emulation), trying to turn off a switched-on toggle button doesn't work. 

https://park-ui.com/docs/panda/components/toggle-group

But if touch somewhere else, it turns off then.

**Comment by cschroeter** [comment]
@dannylin108 

Thanks for taking your time to report this issue.  I've improved the `hover` conditions to only activate on non-touch devices.
A fix will be available in the next release.
