### ISSUE TITLE
[Tailwind] Tabs size prop does not work

### ISSUE THREAD

**Issue by sourcecodes2** [cschroeter/park-ui#295]
Setting the <Tabs> component size prop does not work when using Tailwind with the Parkwind plugin.

For example, setting `<Tabs.Root size="lg">` does not change the size of the tabs.

The component correctly adds the `tabs__root--size_lg` class to the markup, but it appears that all of the tab component size classes are missing and not included in the built CSS.

**Comment by vadamk** [comment]
+1

**Comment by cschroeter** [comment]
With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
