### ISSUE TITLE
Checkbox "colorPalette" prop triggering error (react, tailwind)

### ISSUE THREAD

**Issue by btroop** [cschroeter/park-ui#297]
I copied and pasted the doumented example ([park ui checkbox](https://park-ui.com/docs/tailwind/components/checkbox)) and keep running into this error with the "colorPalette" prop. Scratching my head for workarounds to change the box fill color.

![image](https://github.com/cschroeter/park-ui/assets/18264189/83c1badc-1179-4818-afa1-d3f18eea9633)

**Comment by Curetix** [comment]
I think the docs are incorrect for this component, if you look at the docs for Button (Tailwind variant), they use `className="color-palette_red"` instead of a `colorPalette` prop. I assume the same applies for the checkbox and any other component as well.

**Comment by btroop** [comment]
good idea, though after trying it that method still didn't work for me. I even updated all my packages/components and still can't get it to work

**Comment by itsjavi** [comment]
The problem it might be that the `Checkbox` component is not created with `styled` (`import { styled } from 'styled-system/jsx'`) as the others.

Styled components expose these properties.

**Comment by btroop** [comment]
is that this package?? seems odd to be building a new component library with a deprecated package...

https://www.npmjs.com/package/@styled-system/jsx

**Comment by coopbri** [comment]
> The problem might be that the `Checkbox` component is not created with `styled` (`import { styled } from 'styled-system/jsx'`) as the others.
> 
> Styled components expose these properties.

Thanks @itsjavi, wrapping the checkbox root with `styled` resolved this issue for me. Good catch.

**Comment by cschroeter** [comment]
With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
