### ISSUE TITLE
Feature Request:  Drawer(corvu)

### ISSUE THREAD

**Issue by FlatMapIO** [cschroeter/park-ui#302]
The drawer is a complex component commonly used in mobile terminals. If 'park-ui' implements it, we would no longer need to make an effort to integrate third-party libraries.

links: 
- https://www.solid-ui.com/docs/components/drawer
- https://corvu.dev/docs/primitives/drawer/

**Comment by dannylin108** [comment]
https://park-ui.com/docs/panda/components/drawer

**Comment by FlatMapIO** [comment]
> https://park-ui.com/docs/panda/components/drawer

just a dialog

**Comment by coopbri** [comment]
Not sure why you gave @dannylin108 a thumbs down, he is correct. You can simply add a variant to the drawer that changes its position to the bottom of the screen, such as what my team implemented here: https://github.com/animareflection/ui/blob/master/src/components/core/Drawer/Drawer.recipe.ts#L107-L120

[Demo (Storybook)](https://storybook.animareflection.com/?path=%2Fstory%2Fcomponents-core-drawer--placements)

**Comment by FlatMapIO** [comment]
> Not sure why you gave @dannylin108 a thumbs down, he is correct. You can simply add a variant to the drawer that changes its position to the bottom of the screen, such as what my team implemented here: https://github.com/animareflection/ui/blob/master/src/components/core/Drawer/Drawer.recipe.ts#L107-L120
> 
> [Demo (Storybook)](https://storybook.animareflection.com/?path=%2Fstory%2Fcomponents-core-drawer--placements)

These are two entirely different things, merely sharing the same name. You can refer to https://corvu.dev/docs/primitives/drawer/ for more details; it represents a mobile-native design. It is not a simple dialog.

**Comment by coopbri** [comment]
Thank you for removing the thumbs down, I did see that but it appears to be the same thing except adding draggability (which is easy to implement), even rendering as a div just the same. I understand you seem to be asking about not using other libraries for dragging though, it was just unclear from the OP

**Comment by FlatMapIO** [comment]
For the primary UI, the crucial aspects are anatomy and state machines part, while templates are not of significant importance. Otherwise, @corvu/drawer would not have so much code, even though it is built upon @corvu/dialog.
