### ISSUE TITLE
Cannot install any components with the CLI on Mac CLI

### ISSUE THREAD

**Issue by jeffscottward** [cschroeter/park-ui#304]
Despite having the exact right setup following first PandaCSS w/ Next.js docs instructions found here:
https://panda-css.com/docs/installation/nextjs

And then following the ParkUI docs exactly as found here
https://park-ui.com/docs/panda/overview/getting-started

I still get an error with the CLI 
`npx @park-ui/cli init`

Where it runs just fine until you get to 
`Failed to download utils. Path resolution failed. Please make sure that there is a tsconfig.json file with baseUrl and paths configured.`

Inspite of having a tsconfig that looks like so.
```json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "src",
    "styled-system",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
```

which includes the `baseURL` and `paths` mentioned.

Thoughts?

**Comment by jeffscottward** [comment]
```
 "paths": {
      "~/*": ["./src/*"]
    }
```

is the fix as outline in the `Path Aliases` section.

The Panda bootup may need fixing

**Comment by cschroeter** [comment]
@jeffscottward  The CLI should be able to resolve any path alias. Will ensure there is a test for the new verison.
