### ISSUE TITLE
On Safari the date picker closes after clicking on any date picker element when used inside of a dialog 

### ISSUE THREAD

**Issue by wontondon** [cschroeter/park-ui#305]
**Issue**
When adding a date picker to a dialog and interact with previous and next month controls the date picker it closes immediately after interaction. I've only observed this behavior in Safari. 

**Expected**
Date picker remains open

**Browser**
Safari Version 17.4.1 (19618.1.15.11.14) and also version 16.*

**Examples**
![Screen Recording 2024-05-08 at 12 00 58 PM](https://github.com/cschroeter/park-ui/assets/374289/5fec4e3f-539f-4996-825b-943acc4055c9)

https://stackblitz.com/edit/github-ftdbnx?file=src%2Fapp%2Fpage.tsx

NOTE: stackblitz wasn't really working on Safari so I had to download the files and run it locally.

**Comment by cschroeter** [comment]
@wontondon 

This was fixed in zag-js.com and should no longer be an issue
