### ISSUE TITLE
[Feature Request] - Ability to specify tsconfig filename

### ISSUE THREAD

**Issue by xeinebiu** [cschroeter/park-ui#306]
The issue at the latest version is that we are forced to have tsconfig.json. On NX Monorepo,  that is called tsconfig.base.json on root and I could not find a way how to specify this on parkui config.

I would recommend

```json
{
  "$schema": "https://park-ui.com/schema.json",
  "cssFramework": "tailwind",
  "jsFramework": "react",
  "importAliases": {
    "components": "@/theme",
    "utils": "@/theme"
  },
  "useReactServerComponents": false,
  "tsConfigPath": "...path here"   <--- Suggestion
}

```

**Comment by cschroeter** [comment]
@xeinebiu 

I've updated the CLI so that a tsconfig.json is no longer required to install components. This benefits users with setups like nx workspaces that lack a tsconfig.json file.
