### ISSUE TITLE
[Bug] - ParkUI Tailwind Styles are not inlcuded on NX Monorepo Workspace

### ISSUE THREAD

**Issue by xeinebiu** [cschroeter/park-ui#307]
`parkwindPlugin` does nothing on NX Monorepo.

- Dependencies
````
"@park-ui/tailwind-plugin": "^0.20.1",
 "@ark-ui/react": "^2.2.3",
````

- tailwind.config.js
````javascript
const { parkwindPlugin } = require('@park-ui/tailwind-plugin');

const { createGlobPatternsForDependencies } = require('@nx/react/tailwind');
const { join } = require('path');

module.exports = {
  content: [
    join(
      __dirname,
      '{src,pages,components,app}/**/*!(*.stories|*.spec).{ts,tsx,html}',
    ),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  plugins: [parkwindPlugin],
  darkMode: ['class'],
};

````

- postcss.config.js
````javascript
const { join } = require('path');

module.exports = {
  plugins: {
    tailwindcss: {
      config: join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
  },
};

````javascript

Reference: https://nx.dev/nx-api/react/generators/setup-tailwind

**Comment by cschroeter** [comment]
With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.

**Comment by xeinebiu** [comment]
> With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.

Just posting for anyone if they need help, the solution is to add explicitly the projects that depend on tailwind on the app configuration

const { createGlobPatternsForDependencies } = require('@nx/react/tailwind');
const { join } = require('path');
const { parkwindPlugin } = require('@park-ui/tailwind-plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(
      __dirname,
      '{src,pages,components,app}/**/*!(*.stories|*.spec).{ts,tsx,html}',
    ),
    join('libs/theme/src/lib/**/*.{js,ts,jsx,tsx}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  plugins: [parkwindPlugin],
  darkMode: ['class'],
};
