### ISSUE TITLE
New <Text> component is missing factory and recipe

### ISSUE THREAD

**Issue by alanhoff** [cschroeter/park-ui#308]
Hey, it looks like the new `<Text />` component isn't being wrapped by the jsx factory with `styled()` and it's also not using the `text` recipe anymore. This causes all the JSX style props to just be forwarded into `<Component />`. Is that correct?

https://github.com/cschroeter/park-ui/commit/b809d7a11ec96f312fafef671f5b16f19debe4ce#diff-2b780ab533590cf97f45a899095b095eb2cb695b01810b73719d8b767c6bc1ccR35

**Comment by gal1419** [comment]
probably related to #311

**Comment by cschroeter** [comment]
@alanhoff @gal1419 @marviobezerra

I had to rewrite the [Text](https://github.com/cschroeter/park-ui/blob/main/components/panda/react/src/components/ui/text.tsx) component to avoid using union intersection. Combining `HTMLProps` with `JSXStyleProps` across all possible HTML tags was too complex for TypeScript to handle. The updated component is now available for copy/fetch from the CLI.

**Comment by gal1419** [comment]
Thanks @cschroeter!
