### ISSUE TITLE
The `createStyleContext` function adds significant time to the TS build of an app/library

### ISSUE THREAD

**Issue by brendon1555** [cschroeter/park-ui#31]
I will preface this by saying I'm not actually using `park-ui` directly, but rather just the `createStyleContext` function that I have copied out to my own code from here with my own panda/radix setup.

I was led to the function from the panda docs for compound components: https://panda-css.com/docs/concepts/slot-recipes#styling-jsx-compound-components

I found that when using the `createStyleContext` from here, with its types, it added significant time to the package build, while a version of the function simply using `any` as the input types, added no time.

You can see an example of the build time in this stackblitz: https://stackblitz.com/edit/vitejs-vite-bmphcl?file=src%2Fstyle-context.tsx
This example is using the `createStyleContext` as it is in this repo. The comparison can be seen in the `Select` component by switching out the import for the `simple-style-context` and running another build with `npm run build`.

**Comment by coopbri** [comment]
Thanks for pointing this out, I just realized this was causing my issue too. I am using the style context provider in my design system as well, and the past week or so have  profiled the build and followed the practices in the [TypeScript performance guide](https://github.com/microsoft/TypeScript/wiki/Performance) without luck. As a control test, I finally got the declaration files & declaration source maps to build in ~54 minutes (`DTS ⚡️ Build success in 3274180ms`) with 24GB RAM allocated to the Node build process (of course, I just did this for testing, obviously not practical at all), and changing these types to `any` (specifically factoring out the `AnyProps` and `AnyRecipe` types) dropped the same build to a few seconds.

I won't have time to test until later, but my hunch is that the generics can be rewritten/simplified to get this to work (there are some tips for complex type simplification in the TS performance guide linked above, such as [this](https://github.com/microsoft/TypeScript/wiki/Performance#naming-complex-types)).

**Comment by brendon1555** [comment]
Thanks @cschroeter for looking into it. 

> Which results in a 4s-5s improvement over the initial version. So I am not sure with your example but I also saw a bunch of errors and warnigns in the console running npm run build

Those errors are due to some missing exported types from panda itself, I have raised that one over on the panda repo: https://github.com/chakra-ui/panda/issues/1327
I have added a temporary fix to the stackblitz to resolve the warnings/errors for now.

As for timings, in my linked example, the build time with types generation is ~31s
```
[vite:dts] Start generate declaration files...
dist/style.css      14.43 kB │ gzip:  4.42 kB
dist/preset.es.js    3.70 kB │ gzip:  1.10 kB
dist/index.es.js   126.86 kB │ gzip: 36.72 kB
[vite:dts] Declaration files built in 29079ms.

✓ built in 31.07s
```
But when removing the `dts` plugin from vite to skip generating the types, the build is only ~3s
```
dist/style.css      14.43 kB │ gzip:  4.42 kB
dist/preset.es.js    3.70 kB │ gzip:  1.10 kB
dist/index.es.js   126.86 kB │ gzip: 36.72 kB
✓ built in 2.84s
```

You can also see in the `dist/components/Select/index.d.ts` file that the types are HUGE as they are expanding all the css props for the `styled` components. Whereas `dist/components/Button/index.d.ts` which is also a `styled` component, just not wrapped in context, looks a lot more normal.  (Though I am not sure whether this is being caused by my panda types fix, or this happens anyway...)

@coopbri Would you also be wrapping complex components? And do you get similar results in output `.d.ts` files?

**Comment by cschroeter** [comment]
@brendon1555 got it. I think that this is also the difference between a nextjs app and a component library - d.ts files.
That's why I could not spot any difference in my examination.

Please try 
```tsx
import { createContext, forwardRef, useContext, type ComponentProps, type ElementType } from 'react'

type Props = Record<string, unknown>
type Recipe = {
  (props?: Props): Record<string, string>
  splitVariantProps: (props: Props) => any
}
type Slot<R extends Recipe> = keyof ReturnType<R>
type SlotRecipe<R extends Recipe> = Record<Slot<R>, string>
type VariantProps<R extends Recipe> = Parameters<R>[0]

export interface StyledContextProvider<T extends ElementType, R extends Recipe> {
  (props: ComponentProps<T> & VariantProps<R>): JSX.Element
}

const cx = (...args: (string | undefined)[]) => args.filter(Boolean).join(' ')

export const createStyleContext = <R extends Recipe>(recipe: R) => {
  const StyleContext = createContext<SlotRecipe<R> | null>(null)

  const withProvider = <T extends ElementType>(Component: T, slot?: Slot<R>) => {
    const Comp = forwardRef((props: ComponentProps<T> & VariantProps<R>, ref) => {
      const [variantProps, localProps] = recipe.splitVariantProps(props)
      const slotRecipe = recipe(variantProps) as SlotRecipe<R>
      return (
        <StyleContext.Provider value={slotRecipe}>
          <Component
            ref={ref}
            {...localProps}
            className={cx(slotRecipe[slot ?? ''], localProps.className)}
          />
        </StyleContext.Provider>
      )
    })
    // @ts-expect-error JSX.IntrinsicElements do not have a displayName but Function and Class components do
    Comp.displayName = Component.displayName || Component.name || 'Component'
    return Comp as unknown as StyledContextProvider<T, R>
  }

  const withContext = <T extends ElementType>(Component: T, slot?: Slot<R>) => {
    const Comp = forwardRef((props: ComponentProps<T>, ref) => {
      const slotRecipe = useContext(StyleContext)
      return (
        // @ts-expect-error
        <Component ref={ref} {...props} className={cx(slotRecipe[slot ?? ''], props.className)} />
      )
    })
    // @ts-expect-error JSX.IntrinsicElements do not have a displayName but Function and Class components do
    Comp.displayName = Component.displayName || Component.name || 'Component'

    return Comp as unknown as T
  }

  return {
    withProvider,
    withContext,
  }
}
```

**Comment by cschroeter** [comment]
With this updated version I not just could build your sample project within ~4s also the slot (previously part) is now properly typed. Let me know if you have further optimization for this so I can integrate them.

**Comment by brendon1555** [comment]
:tada: Thanks so much for this! This is a great performance improvement and will be much better for those finding this via the panda docs.

**Comment by olafurns7** [comment]
> ```tsx
> mport { createContext, forwardRef, useContext, type ComponentProps, type ElementType } from 'react'
> 
> type Props = Record<string, unknown>
> type Recipe = {
>   (props?: Props): Record<string, string>
>   splitVariantProps: (props: Props) => any
> }
> type Slot<R extends Recipe> = keyof ReturnType<R>
> type SlotRecipe<R extends Recipe> = Record<Slot<R>, string>
> type VariantProps<R extends Recipe> = Parameters<R>[0]
> 
> export interface StyledContextProvider<T extends ElementType, R extends Recipe> {
>   (props: ComponentProps<T> & VariantProps<R>): JSX.Element
> }
> 
> const cx = (...args: (string | undefined)[]) => args.filter(Boolean).join(' ')
> 
> export const createStyleContext = <R extends Recipe>(recipe: R) => {
>   const StyleContext = createContext<SlotRecipe<R> | null>(null)
> 
>   const withProvider = <T extends ElementType>(Component: T, slot?: Slot<R>) => {
>     const Comp = forwardRef((props: ComponentProps<T> & VariantProps<R>, ref) => {
>       const [variantProps, localProps] = recipe.splitVariantProps(props)
>       const slotRecipe = recipe(variantProps) as SlotRecipe<R>
>       return (
>         <StyleContext.Provider value={slotRecipe}>
>           <Component
>             ref={ref}
>             {...localProps}
>             className={cx(slotRecipe[slot ?? ''], localProps.className)}
>           />
>         </StyleContext.Provider>
>       )
>     })
>     // @ts-expect-error JSX.IntrinsicElements do not have a displayName but Function and Class components do
>     Comp.displayName = Component.displayName || Component.name || 'Component'
>     return Comp as unknown as StyledContextProvider<T, R>
>   }
> 
>   const withContext = <T extends ElementType>(Component: T, slot?: Slot<R>) => {
>     const Comp = forwardRef((props: ComponentProps<T>, ref) => {
>       const slotRecipe = useContext(StyleContext)
>       return (
>         // @ts-expect-error
>         <Component ref={ref} {...props} className={cx(slotRecipe[slot ?? ''], props.className)} />
>       )
>     })
>     // @ts-expect-error JSX.IntrinsicElements do not have a displayName but Function and Class components do
>     Comp.displayName = Component.displayName || Component.name || 'Component'
> 
>     return Comp as unknown as T
>   }
> 
>   return {
>     withProvider,
>     withContext,
>   }
> }
> ```

Hey @cschroeter I like many am using the create-style-context with pure Panda, I get a ton if typescript errors and warnings, for example:

```
Type 'Element' is not assignable to type 'ReactNode'.ts(2322)
index.d.ts(372, 9): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & ProviderProps<SlotRecipe<R> | null>'
```

And more in the similar vein, I'm trying to hack my way through it a bit but any ideas would be cool!
