### ISSUE TITLE
Unexpected token 'T', "The page c"... is not valid JSON

### ISSUE THREAD

**Issue by LauraWebdev** [cschroeter/park-ui#310]
Hey there, wonderful project.

I've tried implementing it in a fresh Laravel Breeze Vue stack. I have followed all setup instructions, and after running the init command I've received the following error. It also prevents me adding any components, returning the same error.

```
│
◇  Failed to fetch components
Failed to download components
Unexpected token 'T', "The page c"... is not valid JSON
```

**Comment by LauraWebdev** [comment]
Seems to be the same issue as #155, @cschroeter was on that.
Were you able to fix this @raymondmuller?

**Comment by cschroeter** [comment]
This has been fixed.
