### ISSUE TITLE
Font size/weight doesn't work?

### ISSUE THREAD

**Issue by gal1419** [cschroeter/park-ui#311]
I've just started using Park-UI for a new project and I love it so far. Thanks for the effort you put into it.

However, I've encountered what seems to be a bug with the Typography component not honoring font sizes. Below is a screenshot from the documentation:

![image](https://github.com/cschroeter/park-ui/assets/12733684/fe1342c3-2454-4927-9c48-ffcfb1c9af0e)

Am I missing anything here?

**Comment by cschroeter** [comment]
Seee #308
