### ISSUE TITLE
prefers-color-scheme and usage of _osDark

### ISSUE THREAD

**Issue by Southclaws** [cschroeter/park-ui#312]
Hey! I'm switching my usage of Park-UI from copying in the templates to just using the preset - mainly to save time and make use of the Radix colour system.

One issue I'm running in to is that it doesn't seem that Park-UI makes use of the native CSS prefers-color-scheme, or in Panda terms: `_osDark` for semantic colours.

I have quite a lot of components using, what was originally, my own `colors.bg.default` token, which used to look like this:

```
      default: {
        value: { base: "{colors.white}", _osDark: "{colors.gray.800}" },
      },
```

And on the docs, I can see both variants of all the default semantic tokens are set up to work with a dark and light mode: https://park-ui.com/docs/panda/theme/semantic-tokens

But I realise you're using a manual toggle rather than prefers-color-scheme:

![image](https://github.com/cschroeter/park-ui/assets/1636971/37e052e7-9e23-4b4b-8737-59d6a3fac098)

While I've considered setting up a manual button in my app, it's not something I'm focusing on at the moment and I'm sticking with the native CSS approach for now.

What I'm wondering is, how can I tell Park-UI's preset to use `prefers-color-scheme` as the driver for switching the semantic token colour source?

**Comment by dannylin108** [comment]
> What I'm wondering is, how can I tell Park-UI's preset to use prefers-color-scheme as the driver for switching the semantic token colour source?

The following works for me:
1. Add this into `panda.config.ts`:
```TS
 //...
 conditions: {
    extend: {
      dark: '.dark &, [data-theme="dark"] &',
      light: '.light &, [data-theme="light"] &',
    },
  }
```

2. Then add `data-theme` attribute depending of system preferences:
```TS
onMount(() => {
    const prefersDarkScheme = window.matchMedia('(prefers-color-scheme: dark)').matches;
    document.documentElement.dataset.theme = prefersDarkScheme  ? 'dark' : 'light';
});
```

**Comment by cschroeter** [comment]
```jsx
export const App = () => {
  return (
    <Box className="dark">
      {/* Renders a Popover component always in dark mode */}
      <Popover />
    </Box>
  )
}
```

This works since 0.39.0

**Comment by renchris** [comment]
@cschroeter 

Did the `0.39.0` update introduce any breaking changes?

My light and dark mode no longer works after updating

```ts
// panda.config.ts
// eslint-disable-next-line import/no-extraneous-dependencies
import { defineConfig } from '@pandacss/dev'
import table from 'recipes/table.recipe'
import globalCss from 'theme'

export default defineConfig({
  preflight: true,
  presets: ['@pandacss/preset-base', '@park-ui/panda-preset'],
  include: ['./src/components/**/*.{ts,tsx,js,jsx}', './src/app/**/*.{ts,tsx,js,jsx}'],
  exclude: [],
  conditions: {
    dark: '.dark &, [data-theme="dark"] &',
    light: '.light &, [data-theme="light"] &',
  },
  globalCss,
  theme: {
    extend: {
      slotRecipes: {
        table,
      },
    },
  },
  jsxFramework: 'react',
  outdir: 'styled-system',
})

```

**Comment by cschroeter** [comment]
@Southclaws 

Could you please try

```jsx
    dark: '.dark &',
    light: ':root &, .light &',
 ```

**Comment by renchris** [comment]
The version `0.39.0` update introduced hardcoded changes to the `conditions` light and dark values with class values exclusive of data-attribute values. See [feat(panda): improve light & dark mode #373 ](https://github.com/cschroeter/park-ui/pull/373/files#diff-101be4113dd45f69473560cc9643f83370d1b3c162508fb5a0c49ba68d5b5ac5).
```diff
// packages/panda/src/conditions.ts
+   dark: '.dark &',
+   light: ':root &, .light &',
```
To override the introduced overriding values and get `data-attribute` for theming working again in `0.39.0` we can use `extend`. See [Customizing Built-in Conditions](https://panda-css.com/docs/customization/conditions#customizing-built-in-conditions).

```diff
  conditions: {
-    dark: '.dark &, [data-theme="dark"] &',
-    light: '.light &, [data-theme="light"] &',
+    extend: {
+      dark: '[data-theme=dark] &',
+      light: '[data-theme=light] &',
    },
  },
```
