### ISSUE TITLE
Fix: datePicker__input without styles in solid js version

### ISSUE THREAD

**Issue by Lenstack** [cschroeter/park-ui#315]
The 'datePicker__input' style class is defined in the date-picker implementation, but it has not been implemented.

![imagen](https://github.com/cschroeter/park-ui/assets/42081538/6b561af8-e51c-4275-8dd4-38cdaa6cb5cc)

![imagen](https://github.com/cschroeter/park-ui/assets/42081538/30b8983c-c4ef-4143-9fdb-ba68a0a49703)

![imagen](https://github.com/cschroeter/park-ui/assets/42081538/6532ad29-7f84-443b-833d-f5a3abaa90b2)

**Comment by cschroeter** [comment]
<img width="658" alt="image" src="https://github.com/cschroeter/park-ui/assets/1846056/5409d061-eccd-40ef-8105-d2d4890196c2">


Should work in the Ark v3
