### ISSUE TITLE
Avatar image being squared

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#319]
https://ark-ui.com/docs/react/components/avatar

![image](https://github.com/cschroeter/park-ui/assets/53458125/3331419e-f604-4e78-8d0d-6f603dec03bd)

**Comment by coopbri** [comment]
Christian resolved this in https://github.com/cschroeter/park-ui/commit/30488b8fd64fb0b5624993fe8d41d2fee48270e2
