### ISSUE TITLE
feat(vue): add create-style-context

### ISSUE THREAD

**Issue by qin-guan** [cschroeter/park-ui#32]
Hey, thanks for the great work, it's really impressive!

I noticed there are no installation guides for other frameworks. Is this on the roadmap or already in the works? 

If it's on the roadmap, I wouldn't mind working on this!

**Comment by cschroeter** [comment]
@qin-guan Thanks for reaching out. 

I would be very happy if we can get more examples and guides on the website. There is already a [early version](https://stackblitz.com/github/cschroeter/park-ui/tree/main/examples/vue/nuxt) that uses nuxt.

What it miss is the Vue version of [create-style-context](https://github.com/cschroeter/park-ui/blob/main/website/src/lib/create-style-context.tsx). I already have a somewhat working [solution](https://github.com/cschroeter/park-ui/pull/29/files#diff-c3e7e108fa76506fdc689b649631846fa39102aa4f2dc50e08b65010c36669be) but it fails to type component props. So if you could help here that would be amazing.

Feel free to reach out on Twitter if you need more insights.

**Comment by qin-guan** [comment]
Hey @cschroeter, thanks for the context! I'll have a look at it as soon as I can and see if I can come up with something 😅

**Comment by qin-guan** [comment]
Hey @cschroeter, I've had a look into it but could not get anything usable out. I could get the props passed down by directly using `ExtractPublicPropTypes` but it does not seem to be recognized by Volar and show up as autocomplete suggestions, so I think this is not the proper way to do it.

Unfortunately my Typescript and Vue internals knowledge is not deep enough to help too much with this, very sorry :(

**Comment by qin-guan** [comment]
```ts
import { mergeProps } from 'vue'
import type { AllowedComponentProps, ComponentCustomProps, IntrinsicElementAttributes, VNodeProps, Component as VueComponent } from 'vue'
import type { HTMLStyledProps, Styled } from '~/styled-system/types/jsx'

type AnyProps = Record<string, unknown>
interface AnyRecipe {
  (props?: AnyProps): Record<string, string>
  splitVariantProps: (props: AnyProps) => any
}

export type DOMElements = keyof IntrinsicElementAttributes
export type ElementType = ReturnType<Styled>

export interface ComponentWithAs<
  Component extends ElementType,
  P extends Record<string, unknown> = Record<never, never>,
> {
  new(): {
    $props: AllowedComponentProps &
    ComponentCustomProps &
    VNodeProps &
    ExtractPropTypes<Component> &
    (Component extends DOMElements
      ? IntrinsicElementAttributes[Component]
      : Record<never, never>) & HTMLStyledProps<Component> &
    P & {
      as?: ElementType
    }
  }
}

export function createStyleContext<
  R extends AnyRecipe, Component extends ElementType,
>(recipe: R) {
  const withProvider = (Dynamic: Component, part?: string) => {
    return defineComponent({
      setup(props, { slots, attrs }) {
        const splittedProps = computed(() => {
          return recipe.splitVariantProps(props)
        })
        const styles = computed(() => {
          const [variantProps] = splittedProps.value
          return recipe(variantProps)
        })

        provide('styles', styles)
        return () => h(
          Dynamic as any,
          { ...mergeProps(attrs, props, { class: styles.value[part ?? ''] }) },
          {
            default: () => slots.default?.(),
          },
        )
      },
    }) as ComponentWithAs<Component>
  }

  const withContext = (Dynamic: Component, part?: string) => {
    return defineComponent({
      setup(props, { slots, attrs }) {
        const styles = inject<ComputedRef<Record<string, string>>>('styles')
        return () =>
          h(
            Dynamic as any,
            { ...mergeProps(attrs, props, { class: styles?.value[part ?? ''] }) },
            {
              default: () => slots.default && slots.default(),
            },
          )
      },
    }) as ComponentWithAs<Component>
  }

  return {
    withProvider,
    withContext,
  }
}
```

This is my current progress, which forwards the props but does work yet with event handlers and `as` prop. It is largely based off existing work from [here](https://github.com/chakra-ui/polymorphic/blob/main/packages/vue/src/polymorphic-factory.tsx). When I have more time, I will try to investigate more 😓

**Comment by cschroeter** [comment]
Ah thats good I think I can come up with something. Thanks @qin-guan  for having a look

**Comment by qin-guan** [comment]
Hey @technorav3nn sorry for the late response. I've actually started a discussion on the Vue repo [here](https://github.com/vuejs/core/discussions/9272) for this specific use case, do feel free to add on for `as` prop or event handlers. If Christian is able to come up with something, I think adding it to docs would be quite helpful for the entire community.

**Comment by technorav3nn** [comment]
@qin-guan I'll see what I can work out, but I agree that it would be very helpful.

**Comment by cschroeter** [comment]
Resolved
