### ISSUE TITLE
docs: does not open file selection dialog

### ISSUE THREAD

**Issue by homemade-ramen** [cschroeter/park-ui#322]
### Description
The file selection dialog on the documentation page for the FileUpload component does not open. This issue prevents file uploads.

### Steps to reproduce
1. Navigate to the documentation page for the FileUpload component. (https://park-ui.com/docs/panda/components/file-upload)
2. Click the Open Dialog button.
3. The dialog box does not open.

### Additional Information
I have identified a potential fix for this issue and will be submitting a pull request shortly. 
Add `FileUpload.HiddenInput`.

**Comment by segunadebayo** [comment]
This is now fixed
