### ISSUE TITLE
Radio Group: Cannot change value - same with Radio Button Group

### ISSUE THREAD

**Issue by marviobezerra** [cschroeter/park-ui#325]
### Steps to reproduce

Copy the sample code from https://park-ui.com/docs/panda/components/radio-group into a new component and try to change the value.

> On the same component, the event `onValueChange` never triggers.

### Same issue with other Components

* Radio Button Group
* Segment Group

### Version

`@ark-ui/react@3.0.2`
`@park-ui/panda-preset@0.37.1`

**Comment by marviobezerra** [comment]
Workaround: downgrading to `@ark-ui/react@3.0.0`

**Comment by coopbri** [comment]
Adding the `RadioGroup.ItemHiddenInput` subcomponent from Ark fixed it for me. See https://github.com/cschroeter/park-ui/blob/main/website/src/components/ui/checkbox.tsx#L34 for reference, and just add it as a child of `RadioGroup.Item`

**Comment by coopbri** [comment]
Oh, just discovered someone else discovered the solution as well here: https://github.com/cschroeter/park-ui/issues/328

**Comment by cschroeter** [comment]
@marviobezerra 
Sorry for the late response. Both examples missed the `HiddenInput` and are fixed now.
