### ISSUE TITLE
Combobox Type Errors: Type 'RootProps' does not satisfy the constraint 'ValidComponent'

### ISSUE THREAD

**Issue by DwieDave** [cschroeter/park-ui#326]
I'm trying to get the combobox to work with my setup:
- Astro `@4.9.2`
- Astro Solid `@4.2.0`
- Solid `@1.8.17`
- ark-ui/solid `@3.0.2`

After adding the combobox using the CLI (which worked great for the Button) 
I'm getting a bunch of typescript errors in the `ui/combobox.tsx`:

<img width="1579" alt="grafik" src="https://github.com/cschroeter/park-ui/assets/15933094/f186de23-2b8c-4095-b3e5-08fcf361d330">

and from those I get the following when I use the ComboBox Components:
 
<img width="1870" alt="grafik" src="https://github.com/cschroeter/park-ui/assets/15933094/5c92f679-1032-4000-92c3-3f08d24d11cd">

While this still works when I run pnpm dev it doesn't build with astro/vite with those errors.

**Comment by DwieDave** [comment]
Initializing Park-UI with `npx @park-ui/cli@latest init` helped with this issue for me. There is still an error in the `combobox.tsx` that got added from the cli (I re-ran the `add` command with the most current version as well)

<img width="1960" alt="grafik" src="https://github.com/cschroeter/park-ui/assets/15933094/adf90c78-4306-4eab-b84f-db3711dbd1ce">

This still prevents me from building this project.

**Comment by cschroeter** [comment]
@DwieDave This should be fixed by now
