### ISSUE TITLE
Solid components with React export

### ISSUE THREAD

**Issue by JericoFX** [cschroeter/park-ui#327]
![Select Component](https://github.com/cschroeter/park-ui/assets/56100605/4c5e822d-c3d7-4c76-8426-591feb61a294)
Some components like Radio Group or even the Select has the react export instead of the ark/solid

[Code](https://github.com/cschroeter/park-ui/blob/main/components/panda/solid/src/components/ui/select.tsx)

**Comment by segunadebayo** [comment]
This is now fixed
