### ISSUE TITLE
[Radio Group] component cannot be selected

### ISSUE THREAD

**Issue by calloc134** [cschroeter/park-ui#328]
Thank you for the wonderful UI library.
## Issue
The radio group component cannot be selected.
In detail, the absence of an input element prevents the component from functioning as a radio button.

## Temporary Solution
Use the ItemHiddenInput component from @ark-ui.

```typescript
import * as RadioGroup from "~/components/ui/radio-group";
import { RadioGroup as RadioGroupArk } from "@ark-ui/react/radio-group";

...

  <RadioGroup.Root name="process">
    {options.map((option) => (
      <RadioGroup.Item
        key={option.value}
        value={option.value}
      >
        <RadioGroup.ItemControl />
        <RadioGroup.ItemText>{option.label}</RadioGroup.ItemText>
        <RadioGroupArk.ItemHiddenInput />
      </RadioGroup.Item>
    ))}
  </RadioGroup.Root>
...
```

## Fundamental Solution
Create an ItemHiddenInput component in park-ui.
The code is as follows.

```typescript
(radio-group.tsx)
...
export const ItemHiddenInput = withContext<
  HTMLInputElement,import { ItemHiddenInput } from "node_modules/@ark-ui/react/dist/components/radio-group/radio-group";
  Assign<JsxStyleProps, RadioGroup.ItemHiddenInputProps>
>(RadioGroup.ItemHiddenInput, "itemHiddenInput");
...
```
In making this change, it is necessary to correct the type of context, which requires modifications to the recipe.

May I create a PR for this issue?
Also, if you have any advice, please let me know.

**Comment by QWu4xYV** [comment]
Also running into this issue. Thanks for reporting it, @calloc134 ; the report made it much easier to find the solution.

Minor suggestion: use

import { RadioGroupItemHiddenInput } from '@ark-ui/react'

instead of 

import { ItemHiddenInput } from "node_modules/@ark-ui/react/dist/components/radio-group/radio-group";

**Comment by calloc134** [comment]
Can I help you with anything?
May I assist you in investigating the cause of this issue?

**Comment by coopbri** [comment]
Related: #325

**Comment by cschroeter** [comment]
@calloc134 

`HiddenInput` was missing. Should be fixed by now
