### ISSUE TITLE
park-ui incompatible with next-css-obfuscator, causing syntax errors

### ISSUE THREAD

**Issue by jac00000b** [cschroeter/park-ui#336]
I'm experiencing an issue when using `park-ui` with `next-css-obfuscator`. The CSS generated by `park-ui` throws syntax errors during the build process with `next-css-obfuscator`. This makes it impossible to use both packages together in a Next.js project.

**Steps to Reproduce:**
1. Set up a new Next.js project.
2. Install `park-ui` and `next-css-obfuscator`.
3. Import and use any component from `park-ui`.
4. Build app
5. Attempt to obfuscate css with `next-css-obfuscator`.

**Expected Behavior:**
The project should build successfully without syntax errors.

**Actual Behavior:**
The build fails with syntax errors related to the CSS generated by `park-ui`.

**Comment by cschroeter** [comment]
@jac00000b 

Sorry I'm not sure what this means.
