### ISSUE TITLE
CLI pulls components that are incompatible with Ark 2

### ISSUE THREAD

**Issue by simoncollins** [cschroeter/park-ui#338]
I have an existing code base using components installed previously and with a dependency on `@ark-ui/react` v2.2.x. Adding new components today (e.g Popover and Carousel) gives me source code that is only compatible with version 3 of Ark as they depend on new exports introduced in that version.

It would be preferable to have the CLI pull from a tag that is compatible with the version of Ark in use, even if it's just the major version. Obviously this is not a show stopper as I can just go and pull the versions pre the change for V3 from Github but it would improve the DX.

**Comment by cschroeter** [comment]
@simoncollins 

Thanks for taking your time to share this issue. A quick fix for this would be to allow the to accept an url endpoint as argument so you could do sth like

```bash
npx @park-ui/cli --url <OLD_ENDPOINT> add pin-input
```

**Comment by simoncollins** [comment]
Thanks @cschroeter ... yeah that would work. I'll put up a PR for that in the next week or so.

**Comment by cschroeter** [comment]
@simoncollins

I've decided not to implement it right now. However, starting with Ark v3, I will ensure backward compatibility
