### ISSUE TITLE
What is the good way to change text color from default palette? (react + tailwind)

### ISSUE THREAD

**Issue by vadamk** [cschroeter/park-ui#340]
Can I do something like this?

`<Text color="tomato-10">...</Text>`

or 

```
import { Settings } from "lucide-react";

<Settings color="red-10" />
```

actually I'm trying to do something like that 
<img width="209" alt="image" src="https://github.com/cschroeter/park-ui/assets/20296237/a2b24cd9-2dbe-4b00-a125-3d0f2c82ad71">

**Comment by cschroeter** [comment]
@vadamk 

With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
