### ISSUE TITLE
[Feature] Use tailwind-radix-colors package

### ISSUE THREAD

**Issue by gnosticdev** [cschroeter/park-ui#346]
First, love the design system for Park UI, and am also a big fan of Radix colors. With that said, as a tailwind user, it is tough to properly add one-off colors bc of the built in tailwind color scheme.

Luckily, someone has already done the hard work of making [tailwind-radix-colors](https://github.com/mrcaidev/tailwindcss-radix-colors) tailwind plugin that replaces all tailwind colors with the Radix colors. Makes things like this available to nicely go with Park's system:

Example: Add alpha accent variation background

Before:
```ts
<div class="text-accent-text bg-[var(--colors-accent-a2)]" />
```
After:
```ts
<div class="text-accent-text bg-jadea-2 dark:bg-jadeadark-2" ... /> 
// has intellisense and uses same scale as the Park color system
```

It also allows for the use of tailwind's opacity modifier that Park is missing.

I haven't gone into the codebase too much yet, but in theory, since both are tailwind plugins it should be fairly straight forward to find a middle ground that enhances Park's tailwind support. 

Either way, love Park UI thanks for putting together! Happy to open a PR if you think it could be useful.

Thanks!

**Comment by cschroeter** [comment]
@gnosticdev 

With a heavy heart, I have decided to discontinue support for Tailwind as the initial maintainer no longer has time to maintain it.
