### ISSUE TITLE
[Feature] Add index file for components folder

### ISSUE THREAD

**Issue by Xelson** [cschroeter/park-ui#350]
This will make it possible to export compound components via the IDE.

Using `Select` as a example, by default it can be exported like this
```ts
import * as Select from '~/components/ui/select'
```

But we can move on to named exports with `index.ts` re-export approach:

**~/components/index.ts:**
```ts
export * as Select from './select';
```

Usage anywhere now:
```ts
import { Select } from './components/ui'
```

**Comment by cschroeter** [comment]
@Xelson 

In `v.0.7.0` the CLI will handle index files. Please give it a shot.
