### ISSUE TITLE
[Button] Button cannot be used as a JSX component.

### ISSUE THREAD

**Issue by tyteen4a03** [cschroeter/park-ui#354]
Getting this error when trying to use Buttons:

<img width="738" alt="Screenshot 2024-06-23 at 14 21 51" src="https://github.com/cschroeter/park-ui/assets/440015/6acdb0fa-1b97-452d-bb99-05b27cf0dcd8">

**Comment by cschroeter** [comment]
@tyteen4a03 

I'm lacking a bit of context. But please checkout the revised component snippets. And try it again.
