### ISSUE TITLE
[Heading] Props are applied but not available via code completion

### ISSUE THREAD

**Issue by corydeppen** [cschroeter/park-ui#357]
When using the `Heading` component, the props are being applied as expected but they do not appear in the code completion list. The only props that appear in the list are `key` and `ref`.

It's also worth noting that, in addition to the `react/display-name` ESLint errors mentioned in #331, there are type errors on both the `Text` and `Heading` components that were installed using the Park UI CLI.

https://stackblitz.com/edit/github-eegtsk?file=src%2Fapp%2Fpage.tsx

**Comment by cschroeter** [comment]
Fixed with 9dcb8bc6092e2275ec095d617fa6e774ca5c9118
