### ISSUE TITLE
Context Error: usePresenceContext return `undefined` when using the Menu component in Solid JS

### ISSUE THREAD

**Issue by jackvane** [cschroeter/park-ui#359]
I'm on Ark UI 3.4.1, Solid Start 1.0.2 and Solid 1.8.18. When using the Menu component like so:

```tsx
function UserMenu() {
  const { user: u } = useAuthContext();

  const user = u();

  if (!user) {
    return null;
  }

  return (
    <Menu.Root>
      <Menu.Trigger class="rounded-full">
        <Avatar name={user.firstName + " " + user.lastName} />
      </Menu.Trigger>

      <Menu.Positioner>
        <Menu.Content>
          <Menu.Arrow>
            <Menu.ArrowTip />
          </Menu.Arrow>

          <Menu.Item value="react">React</Menu.Item>
          <Menu.Item value="solid">Solid</Menu.Item>
          <Menu.Item value="vue">Vue</Menu.Item>
        </Menu.Content>
      </Menu.Positioner>
    </Menu.Root>
  );
}
```

I received the following error:
<img width="1148" alt="Screenshot 2024-07-01 at 7 46 36" src="https://github.com/cschroeter/park-ui/assets/101849104/80f35a1c-2b64-4a83-8a87-f5aa8b932865">

The component was pulled using the cli.

**Comment by jackvane** [comment]
Note this is also an issue for the Dialog component
![Uploading Screenshot 2024-07-01 at 10.59.08.png…]()

**Comment by dannylin108** [comment]
It seems you forgot wrap it with Context or Provider component:

https://ark-ui.com/solid/docs/guides/component-state

**Comment by Lenstack** [comment]
I have the same problem using the cli components.

**Comment by jackvane** [comment]
Isn't the point of the library to be pull and play? I'm not forgetting to wrap anything, it should've already been wrapped.

**Comment by cschroeter** [comment]
@Lenstack 

This should be resolved by now. 

https://github.com/cschroeter/park-ui/assets/1846056/39593f66-ee4a-47bd-847c-4e89f1471b64

**Comment by cschroeter** [comment]
Please check https://github.com/cschroeter/park-ui/tree/main/components/solid/src/components/ui for reference
