### ISSUE TITLE
Pagination: page props is not passed to ArkPagination.Root

### ISSUE THREAD

**Issue by pierrebiver** [cschroeter/park-ui#361]
When using the Pagination component, it seems like there is a bug in how the props are splited which make the `page` props not passed to the root component. It seems to come from the function `splitCssProps` that does not return the page in the `localProps` 
```
const [variantProps, paginationProps] = pagination.splitVariantProps(props)
  const [cssProps, localProps] = splitCssProps(paginationProps) // local props does not contains page.
  ```

**Comment by cschroeter** [comment]
@pierrebiver 

This should be fixed by now https://park-ui.com/react/docs/components/pagination
