### ISSUE TITLE
Figma semantic colors not available by default

### ISSUE THREAD

**Issue by Mottoweb** [cschroeter/park-ui#364]
Using Figma as reference for designs i could not find `bg.success`, `bg.error` and etc defined by the park ui plugin

**Comment by phlzZz** [comment]
You have to use the `bg.neutral.success` & `bg.neutral.error` variables in Figma due to the way I implemented the accent variable mode and distinguish between the neutral and accent color palette.

I did not find a better way to let users choose a specific accent color with native tools in Figma…

**Comment by Mottoweb** [comment]
@phlzZz Makes sense now thanks, but i still find a lot of inconsistencies between park ui and figma variables, like `--spacings-radii` is not even present in park ui anymore, or even `--typography-size-sm` variable is computed to 14px in figma while in park ui using this token results in computed value of 10.5px :/ 

i really like this project and i understand how much effort it took to create, but its a complete bummer to find out the variables in designs are not consistent in park ui..

**Comment by phlzZz** [comment]
I’ll totally understand how you feel. That’s valuable feedback and we‘ll work on aligning them so your experience is better.

**Comment by cschroeter** [comment]
We will add more tokens and align the plugin with the Figma Kit once I add more examples and components. @Mottoweb, you're on the right track. I just need to catch up.
