### ISSUE TITLE
There is no way to easily check the examples code on the new website

### ISSUE THREAD

**Issue by pawojciechowski** [cschroeter/park-ui#368]
I cannot easily check the implementation of the example

![image](https://github.com/cschroeter/park-ui/assets/8688617/5fcb50eb-27a8-4768-8102-499169f48817)

**Comment by itsjavi** [comment]
Same, it was very helpful and a time saver to have those snippets.

**Comment by cschroeter** [comment]
@pawojciechowski @itsjavi 

They will be back shortly. And also available for Solid and Vue.
