### ISSUE TITLE
Docs are missing the "Show Code" button for components

### ISSUE THREAD

**Issue by irishcarbomb777** [cschroeter/park-ui#369]
The Park UI docs used to have a "Show Code" button where you could see an example of the component being used. The button is now gone and there's no obvious way to see an example.

![image](https://github.com/cschroeter/park-ui/assets/15335689/988380e7-bee5-44b8-aa85-d40f61a6cfd2)

**Comment by cschroeter** [comment]
Will be back shortly.

**Comment by irishcarbomb777** [comment]
Thank you!
