### ISSUE TITLE
Is Tailwind CSS no longer available?

### ISSUE THREAD

**Issue by Stradi** [cschroeter/park-ui#370]
Yesterday, there were Tailwind CSS options when copying components from the documentation. They are not available today. Is Tailwind CSS support no longer available?

It seems like commit 88808be or one of the subsequent commits removed the Tailwind CSS versions.

**Comment by coopbri** [comment]
See https://github.com/cschroeter/park-ui/discussions/367

**Comment by cschroeter** [comment]
Maybe at some point in time I find some time but for now this is not maintainable for me. Sorry
