### ISSUE TITLE
Documentation for create-style-context (React) seems to have disappeared from the Docs?

### ISSUE THREAD

**Issue by riceboyler** [cschroeter/park-ui#371]
I'll admit, it's possible I just missed it, but with the newly updated Docs website, I can't find the `create-style-context` documentation anywhere. I ended up having to go into the actual code and copy/paste the React create-style-context.tsx file.

Am I just blind?

**Comment by tclain** [comment]
@riceboyler are you using the tailwind version ?

They discontinued it quietly without warning.

I am working on a fork.

**Comment by linkb15** [comment]
I am searching for the tailwind version as well. I was just using it last week, seems it is gone when I am checking it now.
If you are working on a fork, let me know if I can help anyway on that. So, we all can use it with better support. Thanks

**Comment by riceboyler** [comment]
No, I'm actually using the PandaCSS version.

**Comment by tclain** [comment]
> I am searching for the tailwind version as well. I was just using it last week, seems it is gone when I am checking it now. If you are working on a fork, let me know if I can help anyway on that. So, we all can use it with better support. Thanks

yeah was In the same situation, came back to boot a new subproject and it was gone...

my goal is to republish a fork by august 1st

**Comment by cschroeter** [comment]
@riceboyler

The `create-style-context` function is automatically installed using the CLI. For now, I can point you to the source code, as I haven't added it to the website yet:

- [React](https://github.com/cschroeter/park-ui/blob/main/components/react/src/lib/create-style-context.tsx)
- [Solid](https://github.com/cschroeter/park-ui/blob/main/components/solid/src/lib/create-style-context.tsx)
- [Vue](https://github.com/cschroeter/park-ui/blob/main/components/vue/src/lib/create-style-context.tsx)
