### ISSUE TITLE
How to use the new lazyMount ?

### ISSUE THREAD

**Issue by lilouartz** [cschroeter/park-ui#374]
<img width="498" alt="Screenshot 2024-07-14 at 10 09 28 AM" src="https://github.com/user-attachments/assets/5e555165-cf05-4e88-850d-2f353ba5e1c2">

This used to work, but now I am getting an error saying that children is not a valid property?

**Comment by cschroeter** [comment]
@lilouartz 

Fixed with c532668bdc7727cbc22114cb57e23455172ea8fe. Please dbl check the dialog file
