### ISSUE TITLE
`ref` is not a prop

### ISSUE THREAD

**Issue by gdamou** [cschroeter/park-ui#386]
Hello,

I just got back to a project where I used park-ui in early stage so needed to upgrade everything. After some labour I finished but now there is this issue on React : 

Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

I don't really know if this is relied to park-ui or ark-ui.

It also seems that I can't have more than one Dialog on a rendered page. I don't find any information about this, can someone explain what I need to do ?

**Comment by gdamou** [comment]
It also seems that I can't have more than one Dialog on a rendered page. I don't find any information about this, can someone explain what I need to do ?

**Comment by cschroeter** [comment]
@gdamou

Sorry, mate, I’d love to help, but I need more information. Please re-open the issue and provide a small reproduction so I can assist you better.
