### ISSUE TITLE
Panda `token()` helper returns CSS variable instead of raw value

### ISSUE THREAD

**Issue by Curetix** [cschroeter/park-ui#387]
Hello there, I'm trying to get the raw color value of a Park UI token using Panda's `token()` helper, but I only get the CSS variable like `var(--colors-bg-default)`. The generated code in `styled-system/tokens/index.mjs` contains the correct values for "native" Panda tokens, but not (what I assume) Park UI tokens:
```tsx
const tokens = {
  // ....
  // Native Panda:
  "sizes.full": {
    "value": "100%",
    "variable": "var(--sizes-full)"
  },
  // ....
  // Park UI:
  "colors.bg.default": {
    "value": "var(--colors-bg-default)",
    "variable": "var(--colors-bg-default)"
  },
  // ....
```
Cheers!

**Comment by cschroeter** [comment]
@Curetix I'm not sure If I fully understand but here is what I use in Park to resolve the raw value of a token:

```jsx
import { token } from 'styled-system/tokens'

const rawValue =  token.var('colors.accent.a11')
console.log("--colors-accent-text",  rawValue)
```

**Comment by cschroeter** [comment]
`colors.bg.default` is a semantic token. I think there is a bit more to do.
