### ISSUE TITLE
Listing a component with .map doesn't apply any styles

### ISSUE THREAD

**Issue by JUNNNI** [cschroeter/park-ui#388]
Description:

I have encountered an issue when dynamically calling a component using .map. Indeed this unfortunately doesn't apply any style. 
When I replace hardcoded component instances with a dynamically generated list using .map, the styles are not applied as expected.

Steps to Reproduce:

- Update the story `icon.stories.tsx` and define the sizes in an array such as below
- Turn off Storybook and restart it after changes (`bun react storybook`). This will avoid pre-generated styles to be applied.
- Observe that the styles are not applied properly.

This might be an issue related to PandaCSS.
Thanks a lot for your help

````tsx
import type { Meta } from '@storybook/react'
import { DiamondIcon } from 'lucide-react'
import { Box, HStack,} from 'styled-system/jsx'
import { Icon, Text } from '~/components/ui'

const meta: Meta = {
  title: 'Components/Icon',
}

export default meta

export const Base = () => (
  <Icon>
    <DiamondIcon />
  </Icon>
)

// This works
// export const Sizes = () => (
//   <Stack>
//      <Icon size="xs">
//       <DiamondIcon />
//     </Icon>
//     <Icon size="sm">
//       <DiamondIcon />
//     </Icon>
//     <Icon size="md">
//       <DiamondIcon />
//     </Icon>
//     <Icon size="xl">
//       <DiamondIcon />
//     </Icon>
//     <Icon size="2xl">
//       <DiamondIcon />
//     </Icon>
//   </Stack>
// )

// This doesn't
const sizes = ['xs', 'sm', 'md', 'lg', 'xl', '2xl']

export const Sizes2 = () => (
  <HStack gap={5} alignItems="end">
    {sizes.map((size) => (
      <Box key={size} textAlign="center">
        <Icon size={size}>
          <DiamondIcon />
        </Icon>
        <Text fontSize="sm">{size}</Text>
      </Box>
    ))}
  </HStack>
)

**Comment by JUNNNI** [comment]
### Update

I noticed something strange. If I removed the `lg` size from the array, it works well. 
However, looking at the `recipes/icon.ts` file, the size `lg` is well defined.
 
```ts
import { defineRecipe } from '@pandacss/dev'

export const icon = defineRecipe({
  className: 'icon',
  base: {
    color: 'currentcolor',
    display: 'inline-block',
    flexShrink: '0',
    verticalAlign: 'middle',
    lineHeight: '1em',
  },
  defaultVariants: {
    size: 'md',
  },
  variants: {
    size: {
      xs: {
        w: '3',
        h: '3',
      },
      sm: {
        w: '4',
        h: '4',
      },
      md: {
        w: '5',
        h: '5',
      },
      lg: {
        w: '6',
        h: '6',
      },
      xl: {
        w: '7',
        h: '7',
      },
      '2xl': {
        w: '8',
        h: '8',
      },
    },
  },
})

```

**Comment by Curetix** [comment]
Yes, this is probably a Panda limitation. This page in the docs seems relevant: https://panda-css.com/docs/guides/dynamic-styling#jsx-style-props

**Comment by cschroeter** [comment]
@Curetix 

100%

**Comment by JUNNNI** [comment]
Thank you, that was it! I ended up generating the recipes styles in the config as follows:
https://panda-css.com/docs/guides/static#generating-recipes
