### ISSUE TITLE
support tsconfig.json references

### ISSUE THREAD

**Issue by s97712** [cschroeter/park-ui#390]
Here’s my tsconfig.json file. I’m referencing other configurations, but park-ui isn’t handling it properly.

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.node.json"
    }
  ]
}

```

**Comment by Soufou69** [comment]
Hey,
You should check this : #377

**Comment by cschroeter** [comment]
@s97712 @Soufou69

Resolving `tsconfig.json` might not be the best approach. Instead, if a "valid" tsconfig isn't found, we should prompt the user for a path alias and its resolution.

Example:
```json
"paths": {
  "~/*": ["./src/*"]
}
```

We can then save the alias and path (value) in `park-ui.json`.

### Updated Park UI Configuration
```json
{
  "$schema": "https://park-ui.com/registry/latest/schema.json",
  "importAlias": "~/*",
  "jsFramework": "react",
  "outputPaths": {
    "componentsDir": "~/components/ui",
    "libDir": "~/lib"
  },
  "paths": {
    "~/*": ["./src/*"]
  }
}
```

**Comment by cschroeter** [comment]
@s97712 @Soufou69

I've updated the CLI so that a tsconfig.json is no longer required to install components. This benefits users with setups like nx workspaces that lack a tsconfig.json file.
