### ISSUE TITLE
tooltip recipe missing z-index

### ISSUE THREAD

**Issue by dannylin108** [cschroeter/park-ui#395]
Tooltip content should have 'popover' zIndex to be above usual content.  

 @park-ui/panda-preset 0.41.0

**Comment by piyanggoon** [comment]
![CleanShot 2567-07-30 at 22 52 27@2x](https://github.com/user-attachments/assets/c506651e-679e-47cd-9287-2bfe45176b79)

![CleanShot 2567-07-30 at 22 52 44@2x](https://github.com/user-attachments/assets/4b96d4c6-1d3e-46f3-ae79-1b15fc640828)

Same issue (react).

**Comment by cschroeter** [comment]
@piyanggoon @dannylin108 

Thanks will be fixed in  `0.42.0`
