### ISSUE TITLE
[CLI] Files paths are poorly matched

### ISSUE THREAD

**Issue by abdulahd2008** [cschroeter/park-ui#396]
While running cli to add components, many of the file paths are not precedded with the custom aliases (@/~), this causes undesirable issues, this happened with `styled-system`, I spend a over a half and hour figuring out why I am getting module found, I even installed the `styled-system` npm package, as I thought the CLI have missed it, than after half and hour banging my head and figuring out why it doesn't working, My eyes fell on the styled-system directory, and then preceding with the custom aliases fixed the problem, there are many other issues in the document as well, I am not here to critisize the component library, I am just reporting what other may face in future, also I love park ui

**Comment by abdulahd2008** [comment]
- [tokens] Missing token: `colors.red.9` used in `theme.semanticTokens.colors.border.error`
- [tokens] Missing token: `colors.red.9` used in `theme.semanticTokens.colors.fg.error`


Also these errrors in the config

**Comment by abdulahd2008** [comment]
> While running cli to add components, many of the file paths are not precedded with the custom aliases (@/~), this causes undesirable issues, this happened with `styled-system`, I spend a over a half and hour figuring out why I am getting module found, I even installed the `styled-system` npm package, as I thought the CLI have missed it, than after half and hour banging my head and figuring out why it doesn't working, My eyes fell on the styled-system directory, and then preceding with the custom aliases fixed the problem, there are many other issues in the document as well, I am not here to critisize the component library, I am just reporting what other may face in future, also I love park ui

Yes, have added `styled-system` to include array in typescript config file

**Comment by cschroeter** [comment]
@abdulahd2008 

I've updated the CLI so that a` tsconfig.json` is no longer required to install components. This benefits users with setups like `nx` workspaces that lack a `tsconfig.json` file.
