### ISSUE TITLE
[Package] Panda preset invalid tokens 

### ISSUE THREAD

**Issue by A1X5H04** [cschroeter/park-ui#404]
🐼 warn [config] ⚠️ Invalid config:
- [tokens] Missing token: `colors.red.9` used in `theme.semanticTokens.colors.fg.error`
- [tokens] Missing token: `colors.red.9` used in `theme.semanticTokens.colors.border.error`

----

This creates trouble when showing errors in forms and toasts, please fix it as soon as you can

**Comment by cschroeter** [comment]
@A1X5H04 

Thanks for reporting. Please update to `0.42.0`
