### ISSUE TITLE
feat: table component

### ISSUE THREAD

**Issue by Attk4** [cschroeter/park-ui#42]
Hello, thanks for the great work!

Any chance for a table component anytime?

Thanks.

**Comment by cschroeter** [comment]
@Attk4 

Thanks for taking your time to create this issue.

I think a table is a good addition. But it would only contain the UI not the logic. Would you be interested in a classic table (table,th, td, tr) or a modern table using grid / flex?

**Comment by Attk4** [comment]
Coming from shadcn, I really like their simple Table component (table, th, td, tr tags and just adding style on top of them), and also having the more-advanced DataTable (table, th, td, tr + style + tanstack table). 
For a start I think the simple Table would be more than enough, and as people are in a need of a more performant solution, adding support for the DataTable component as well, maybe even a modern table using grid/flex, but I personally prefer the classic tables.

**Comment by Attk4** [comment]
Hello!

Thank you for the fast response and implementation, looks great! Can you also release/publish it on npm by any chance? 😄 

Thank you again!
