### ISSUE TITLE
How do you extend the preset?

### ISSUE THREAD

**Issue by elmarvr** [cschroeter/park-ui#45]
For instance adding a new variant to the table recipe

**Comment by sparten11740** [comment]
The same way as you would extend any other configuration in panda-css. Be aware that some components are defined as `recipes` (input, button, ...), and some as `slotRecipes` (select, table, ...). Example of adding a new size variant to the table recipe:
```js
// panda.config.js
export default {
  // ... rest of the config
  theme: {
    extend: {
      slotRecipes: {
        table: {
          variants: {
            size: {
              lg: {
                root: {
                  textStyle: 'lg'
                }
              }
            }
          },
        }
      }
    }
  }
}
```

**Comment by cschroeter** [comment]
Thanks for taking your time to create the issue and thanks for taking your time @sparten11740 to answer this one. 

Depending on your usecase it is also an option to copy the full recipe in your project and **overwrite**  the table recipe like so:

```tsx
 theme: {
    slotRecipes: {
      table: {
        // create your own table styles (not extending!)
      }
    }
  }
  ```
  
  I plan to extend the documentation as soon as the new website is live
