### ISSUE TITLE
park-ui seems to require bun as a dependency

### ISSUE THREAD

**Issue by asabil** [cschroeter/park-ui#474]
Using park-ui as a project dependency seems to now require `bun` to be installed, this this expected?

```
npm error code 127
npm error path .../node_modules/@park-ui/panda-preset
npm error command failed
npm error command sh -c bun run build
npm error sh: 1: bun: not found
```

This seems to be related to the `postinstall` script:

```
5733 info run @park-ui/panda-preset@0.43.0 postinstall node_modules/@park-ui/panda-preset bun run build
```

**Comment by cschroeter** [comment]
@asabil 

Thanks for reaching out. If you install the Park UI Preset you should not see this. The `postinstall` script should be removed by
 ```json
  "clean-package": {
    "remove": ["scripts.postinstall"]
  }
  ```
  
  If you wan to fork it or work with it locally, yes you need bun.

<img width="596" alt="image" src="https://github.com/user-attachments/assets/677c99be-df99-4b76-b0b7-8b749c199b09">

**Comment by asabil** [comment]
That wasn't forked at all, that was just a normal project dependency.

**Comment by nmiljkovic** [comment]
@cschroeter I get the same issue. When I download the tgz from npm, you're right, there is no postinstall script.

However you can look at the registry definition here: https://registry.npmjs.org/@park-ui%2fpanda-preset

For versions 0.43.0 and 0.43.1, it does show the `postinstall` script. I'm assuming that `npm` actually reads this metadata and not the shipped `package.json` in the tgz :open_mouth: 

![image](https://github.com/user-attachments/assets/37cec569-1045-4abc-a4d7-1085cf781a14)

**Comment by capJavert** [comment]
@cschroetergit the same issue here, this is a bug, could you guys look into fixing this?

**Comment by bohdanbirdie** [comment]
Issue is still present, @cschroeter 
```
npm error code 1
npm error path /.............../node_modules/@park-ui/panda-preset
npm error command failed
npm error command sh -c bun run build
npm error $ tsup
npm error Cannot find src/index.ts,src/colors/*.ts,src/utils/index.ts
npm error error: script "build" exited with code 1
```

**Comment by Loque-** [comment]
Hiya, also ran into this issue today (same as opening poster)

**Comment by bohdanbirdie** [comment]
@cschroeter can this get re-opened? Issue is still there

**Comment by vincehi** [comment]
I also have the problem, I think the ticket should be reopened.

**Comment by vincehi** [comment]
npm i @park-ui/panda-preset@0.43.1 --ignore-scripts

**Comment by SpencerDuball** [comment]
I tried this today after switching from pnpm to npm, for some reason pnpm has no issue with this - but npm does.

**Comment by vincehi** [comment]
The problem still exists, I think it needs to be reopened.

**Comment by dcousineau** [comment]
Confirming that while running `npm pack @park-ui/panda-preset` the tarball does _not_ show a `postinstall` command in the package.json, it still attempts to run the post-install. @nmiljkovic is 100% correct that the discrepancy on the registry is where the command is coming from. 

Unfortunately @cschroeter you've _accidentally_ stumbled across the "manifest confusion" attack on npm that [Darcy Clarke has identified and written about](https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem). I believe that `clean-package` is insufficient for its purpose as while it correctly alters the package.json before packing the tarball, it sadly does not swap before the "incorrect" package.json is published to the manifest registry.
