### ISSUE TITLE
Missing additionalColors property in createPreset function

### ISSUE THREAD

**Issue by vitorGabr** [cschroeter/park-ui#485]
The createPreset function should accept and process the additionalColors property, allowing additional colors to be included in the preset.

createPreset({
      accentColor: grass,
      grayColor: sand,
      radius: 'lg',
      additionalColors: ['*'],
    }),

**Comment by jprieur** [comment]
Its appears that the `additionalColors` option is gone and that these should be added directly in your theme. For instance, if you want to add green, you'd import it and inject it in your theme as seen below.

Not sure about how to replace the wildcard behavior of `additionalColors` though.

```js
import grass from "@park-ui/panda-preset/colors/grass";
import sand from "@park-ui/panda-preset/colors/sand";
import green from "@park-ui/panda-preset/colors/green";

export default defineConfig({
  presets: [
    createPreset({
      accentColor: amber,
      grayColor: slate,
    }),
  ],

  theme: {
    extend: {
      tokens: {
        colors: {
          green: green.tokens,
        },
      },
      semanticTokens: {
        colors: {
          green: green.semanticTokens,
        }
      }
    }
  }
 });
```
