### ISSUE TITLE
[BUG] [Website] Theme Generator issue

### ISSUE THREAD

**Issue by sozonome** [cschroeter/park-ui#49]
## Description

1. Copy Config feature of Theme Generator is only visible at dark mode [preview attached below]
2. Copy Config not showing when opened through navbar [preview attached below]

## Preview

https://github.com/cschroeter/park-ui/assets/17046154/c15ddbd8-63c2-4ef1-b570-61b56b52ae96

**Comment by cschroeter** [comment]
Hey buddy,

The landing page has been relaunched. So the issue should be gone by now. Regarding the `copy config` feature, with the next release you can do sth like this:

```tsx
presets: [
  parkPreset( { grayColor: "slate", accentColor: "indigo", borderRadii: "sm" } )
]
```

So there should be not a need to copy the previous boilerplate. Of course you can still extend the theme / preset like you always can, but this should give most folks a good quickstart.
