### ISSUE TITLE
(React): Add use client in the copy paste example

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#51]

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. 

I'm a bit hesistant with this proposal since not all frameworks do this `use client` thing (e.g. CRA, Astro, Vite etc)

I need to think about a good way to handle this.

**Comment by cameronelliott** [comment]
I'm just learning about this, but it looks like 'use client' might just be in the React Canary release channel at this time, unless of course it has migrated to the stable release, and they haven't updated the docs.

https://react.dev/reference/react/use-client
https://react.dev/blog/2023/05/03/react-canaries

But it seems like after 'use client' gets into stable, it would be nice to have this on such components.

**Comment by juliomuhlbauer** [comment]
Yes, it is the Canary channel. But does it make a diference in the stable version?

**Comment by cschroeter** [comment]
@juliomuhlbauer 

This will be part of the upcoming CLI.
