### ISSUE TITLE
[Make it yours]: Copy Config missing from the new website

### ISSUE THREAD

**Issue by hamzaabamboo** [cschroeter/park-ui#53]
Hi, I tried to find copy config and it was missing from the dialog. (Though i think if i trace back to next.js version it's there)

<img width="1799" alt="スクリーンショット 2023-10-05 10 12 22" src="https://github.com/cschroeter/park-ui/assets/3754620/8bdf36e3-e529-433b-98f0-bf3a81eacfa8">

Would love to help contribute btw, amazing library

**Comment by cschroeter** [comment]
Hey buddy,

Thanks for taking your time to create this issue. This change is somewhat intentional. With the next release  you simply can do something like:

```tsx
presets: [
  parkPreset( { grayColor: "slate", accentColor: "indigo", borderRadii: "sm" } )
]
```

So there should be not a need to copy the previous boiler plate. Of course you can still extend the theme / preset like you always can, but this should give most folks a good quickstart.

**Comment by hamzaabamboo** [comment]
Thank you for the explanation. For time being i went ahead and copied the configuration generated by older version 😅.

**Comment by cschroeter** [comment]
@TreeOfLearning You can find the latest changes here https://park-ui-website-qd3qxlhni-cschroeter.vercel.app/

I need a bit more time to improve the recipes but after that it should be fine :)

**Comment by vexxvakan** [comment]
> @TreeOfLearning You can find the latest changes here https://park-ui-website-qd3qxlhni-cschroeter.vercel.app/
> 
> I need a bit more time to improve the recipes but after that it should be fine :)

I dabbled with Park UI just now to realise that neither createPreset nor parkPreset exist in the current build. Any ideas?

**Comment by cschroeter** [comment]
@vexxvakan 

I will need to test and document the latest changes. Mostly around the new color presets (Radix UI). But its pretty much ready.
