### ISSUE TITLE
How to use `createStyleContext`?

### ISSUE THREAD

**Issue by chrisabrams** [cschroeter/park-ui#56]
I was reading the docs on the tabs, and I noticed there is a part where you need to pull in `createStyleContext` for the tabs if you are using React. I tried copying the demo, and also copying the `createStyleContext` from the website section in Github. However, I get an error: `proxyState is not iterable` -- if someone knows how to create a codesandbox or stackblitz with React + Panda, I'll make a reproduction.

**Comment by cschroeter** [comment]
This error is often caused by having multiple versions of Ark UI in your project setup. Please kindly check

**Comment by chrisabrams** [comment]
You are correct there are multiple versions of `@ark-ui/react`. `@pandacss/studio@npm:0.16.0` is loading `@ark-ui/react@0.9.0` whileI have installed `@ark-ui/react@0.15.0`.

I thought `@pandacss/studio` was just for documentation. I can force Vite to use the higher version and see if that works.

**Comment by cschroeter** [comment]
We will investigate on how to resolve that issue or at least document it. Thanks for taking your time to report back to us
