### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by jimjamdev** [cschroeter/park-ui#57]
![IMG-20231016-WA0000.jpg](https://github.com/cschroeter/park-ui/assets/797547/b5d8a611-74df-46cc-998a-4fad86e4b61d)

Getting a lot of build errors here on local and vercel. This is using the setup from https://stackblitz.com/github/cschroeter/park-ui/tree/main/examples/react/next-js

Dev works fine locally. 

You can ignore the next Auth error right now, seems a package update borked something.

Any ideas about these styled-system paths not being found?

**Comment by jimjamdev** [comment]
Ok fixed. I had to move the styled-system folder to /src

**Comment by cschroeter** [comment]
Glad you could solve the issue.
