### ISSUE TITLE
broken link to components

### ISSUE THREAD

**Issue by gdamou** [cschroeter/park-ui#59]
Hello,

When you search on google a component with for example "park ui dialog" you'll get the first result to be like : 

https://park-ui.com/docs/components/dialog

But since you added a new css framework, page will return 404 not found. I tried to fix it but I got some problem making the project work on my side. It would be nice if you were able to setup a contribute md so people would help you on this awesome project.

Thanks for your great work with Park UI, i love using it !

**Comment by cschroeter** [comment]
Hey @gdamou 

Thanks for taking your time to report this issue. I've tried to resolve this using Astro's redirect mechanics but I had no lock. If you want you can create a little 404 like https://panda-docs.vercel.app/404

Hopefully Google updates the sitemap soonish :D
