### ISSUE TITLE
Visibility of tailwind styles

### ISSUE THREAD

**Issue by DawidWraga** [cschroeter/park-ui#61]
Hi,

I really like the fact that tailwind option is being added to park-ui. Thank you for your hard work on this!

One concern I have is the ease of changing recipe styles.

I really like that in the panda version all of the styles are clearly visible. If I want to make a component fully custom, I just copy/paste the recipe from the docs and tweak it to my needs. This clear visibility of default styles and ease of customisation is why I am using park-ui in the first place.

In contrast, the tailwind recipe definition hides the actual style definitions and I'm not sure how I'd change any of the default styles. This makes the DX much worse in my option, but perhaps I am missing something here - please let me know.

**Comment by sholzmayer** [comment]
There are some ways to customize the tailwind styles. You can find it in the [documentation](https://park-ui.com/docs/tailwind/overview/customize). 
However, currently, there is no way to eject the css classes on a recipe basis.
