### ISSUE TITLE
SolidJS component issues.

### ISSUE THREAD

**Issue by charmbyte** [cschroeter/park-ui#64]
I mentioned it in the ArkUI issues, but I am not able to replicate many of the components in SolidJS at this point due to the Ark SolidJS package release version being stuck at 0.11.0. Until Ark updates the SolidJS package, it may be worth noting somewhere that many of the ParkUI SolidJS components will not work using the examples on the website.

Thanks for all your hard work!

**Comment by cschroeter** [comment]
We just launched v1.0.0-beta.0 for Ark UI 

A Park UI release will follow shortly. Thanks for being patient

**Comment by charmbyte** [comment]
@cschroeter Unfortunately installing @ark-ui/solid@beta isn't working. It's requesting the workspace dependency for @ark-ui/anatomy. I'm wondering if maybe it needs a dependency link to the package version of @ark-ui/anatomy to be published to npm. I'm not an expert in monorepo structure, especially when published to npm, so maybe I'm misunderstanding something. And I know this isn't the Ark issues area, but I figured it fit in this conversation.

**Comment by cschroeter** [comment]
@charmbyte 

Good catch. Please use `1.0.0-beta.1`

**Comment by charmbyte** [comment]
@cschroeter It installs just fine now.

The issue I'm having now is that if I use ParkUI in my own monorepo, I get a type serialization error when generating types for components using the ```create-style-context``` script from your examples. I'm guessing that for non-monorepo people, this may not be a problem since it builds the JavaScript just fine -- it's only when generating types that I'm getting the issue.

**Comment by cschroeter** [comment]
@charmbyte 

If you can provide me an example I can look at - I would be happy to help

**Comment by cheelahim** [comment]
@cschroeter in the docs there is a following example:
```ts
import { ark, type HTMLArkProps } from '@ark-ui/solid'
import { type VariantProps } from 'tailwind-variants'
import { styled } from '~/lib/styled'
import { codeStyles } from './recipe'
```
When the Tailwind plugin is used, where does the `~/lib/styled` come from?

**Comment by futbotism** [comment]
+1 for solid issues

any component that requires these type of definitions don't seem to work correctly, i wonder if its something to do with me having a wrong version of `@ark-ui/solid` installed? perhaps one with breaking changes

```
import * as Ark from '@ark-ui/solid/dialog'
//...
export * from '@ark-ui/solid/dialog'

```

these are my current versions...
"@ark-ui/solid": "^1.0.0-beta.2",
"@park-ui/panda-preset": "^0.19.0",
"@pandacss/dev": "^0.16.0",

_btw thanks for an awesome library i love the ideas here_

**Comment by cschroeter** [comment]
@sholzmayer

Can you please advice

**Comment by sholzmayer** [comment]
Hey @cheelahim, you can check out the [example projects](https://park-ui.com/docs/tailwind/overview/getting-started/) for Tailwind. There are some React examples with the lib/styled file. Working on adding a SolidJS example, although it's not available yet. The concept of React's styled file might still be useful to you.

**Comment by cschroeter** [comment]
Looks like everything is working for now. Please open a new issue if needed
