### ISSUE TITLE
Recipes are not being generated on latest version

### ISSUE THREAD

**Issue by kaumac** [cschroeter/park-ui#68]
Hey all, first of all thanks so much for the hard work on park-ui!

I'm doing a fresh install and tried using the latest version. It seems that on the latest version the `styled-system/recipes` directory and files are not being generated.

I tried older versions of both park-ui and pandacss and it seems that this issue only happens on the latest (v0.19.0) version of park-ui. (works fine with 0.18.0 for example)

**Comment by emckay** [comment]
+1 also broken for me.

```
    "@park-ui/panda-preset": "^0.19.0",
    "@pandacss/dev": "^0.17.0",
```

**Comment by cschroeter** [comment]
@kaumac 

Thanks for taking your time to create this issue. With`v0.20.0` I've  added a default export to `@park-ui/panda-preset` for easier configuration. This will use `neutral` as accent and gray color with `borderRadius` of `sm`.

```jsx
import { defineConfig } from '@pandacss/dev'

export default defineConfig({
  presets: ['@pandacss/preset-base', '@park-ui/panda-preset'],
  // ...
})
```

To customize the Park UI preset, use the `createPreset` function as shown below:

```jsx
import { defineConfig } from '@pandacss/dev'
import { createPreset } from '@park-ui/panda-preset'

export default defineConfig({
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'amber',
      grayColor: 'sand',
      borderRadius: 'none',
    }),
  ],
  // ...
})
```

I've also updated all examples so if you still run into issue please check them for reference e.g. [Astro](https://stackblitz.com/github/cschroeter/park-ui/tree/main/examples/panda/react/astro?file=panda.config.ts)

**Comment by kaumac** [comment]
Thanks for this @cschroeter. PS: It would be great to have this information on the documentation. Like a "How to customize" page.
I'm a bit busy atm but I can open a PR for this sometime next month.

Thanks again for the great work!
