### ISSUE TITLE
feat: add vscode extention based on the Park UI CLI

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#71]
VS Code snippets extension:

https://twitter.com/nrjdalal_dev/status/1717765244720738791

**Comment by cschroeter** [comment]
That is really cool. I much like prefer this over a CLI - lovely. Thanks for sharing

**Comment by sholzmayer** [comment]
I just had a look at the extension's source code and it makes use of the current CLI to handle all its operations. So they have both: the CLI and the vscode extension on top of it. 
I like that approach, because then it is not limited on vscode.

**Comment by Blinks44** [comment]
> I just had a look at the extension's source code and it makes use of the current CLI to handle all its operations. So they have both: the CLI and the vscode extension on top of it. I like that approach, because then it is not limited on vscode.

Same, after using Webstorm for awhile, for me others editors became garbage, so cli is must have tool. 

Is cli documented in Park-ui website or it is under development?

**Comment by sholzmayer** [comment]
I'm working on a CLI, stay tuned 🚀

**Comment by cschroeter** [comment]
https://twitter.com/selemondev/status/1747106089710014717
