### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by shiftlabs1** [cschroeter/park-ui#75]
Hi @cschroeter , I am sure you anticipate this question (or one in the form of any plans to support 'X') but am asking any way for svelte. Is there any plans to support svelte. On my part i am going to look at the Vue bit and see how i can transition that to svelte

**Comment by baseplate-admin** [comment]
hi why was this closed?

**Comment by cschroeter** [comment]
Sorry forgot to add that we need to wait for https://github.com/chakra-ui/ark/tree/main/packages/svelte to be implemented.

**Comment by baseplate-admin** [comment]
hi, thanks for fast response.

> Sorry forgot to add that we need to wait for https://github.com/chakra-ui/ark/tree/main/packages/svelte to be implemented.

But should this issue not be kept open till then?

With something like

Blocked by XXX PR?

**Comment by cschroeter** [comment]
Sorry this is not Jira.

**Comment by joshua1** [comment]
Ark UI now has full svelte support . Any plans to pull that in to Park UI ?
