### ISSUE TITLE
Park UI Tailwind CSS Plugin

### ISSUE THREAD

**Issue by gurkerl83** [cschroeter/park-ui#76]
Have a quick question, is it correct that your Park UI Tailwind CSS Plugin uses Panda CSS under the hood? Does that mean using tailwind-variants with ark from your examples produces build time generated styles?

Thx for clarifying!

**Comment by cschroeter** [comment]
@sholzmayer cc

**Comment by sholzmayer** [comment]
The tailwind plugin uses the static css file, that is created before the plugin is published, from the park-ui panda preset. However, you can customize it, see in the [docs](https://park-ui.com/docs/tailwind/theme/customize/).

But remember, the plugin will use the park-ui panda preset and won't consider any custom panda CSS recipes you might have created!
