### ISSUE TITLE
Missing Arc types using Arc components with createStyleContext / withProvider

### ISSUE THREAD

**Issue by gurkerl83** [cschroeter/park-ui#87]
Using an Arc component with createStyleContext respectively the returned HOC withProvider function the returned Component is stripped from typescript types previously assigned to an Arc component.
 
Ark direct use:
```
<Ark.Combobox.Root onInputValueChange={handleChange} // onInputValueChange available
```

Signature of callback
```
onInputValueChange?: (details: InputValueChangeDetails)
```

Park indirect use:
```
const ComboboxRoot = withProvider(Ark.Combobox.Root, 'root'); // using withProvider looses types assigned to Ark.Combobox.Root

<ComboboxRoot onInputValueChange // onInputValueChange not recognised by typescript
```

The identical behaviour can be observed creating a new Object Combobox and setting the Root slice to ComboboxRoot and using it later

```
export const Combobox = Object.assign(ComboboxRoot, {
  Root: ComboboxRoot,
  ...
});

<Combobox.Root onInputValueChange // onInputValueChange not recognised by typescript
```

**Summary:**
Wrapping `Ark.Combobox.Root` in `withProvider` and using the returned component in an app will not have any types available defined in Ark.Combobox.Root, this happens with all Arc components.

**Comment by cschroeter** [comment]
@gurkerl83 

Thanks for taking your time to report this issue. I will have a look shortly.

**Comment by cschroeter** [comment]
@gurkerl83 

I'm not able to reproduce the issue described by you (see attachment)
Can you verify that you use the latest `create-style-context` and provide me an example to look at?

<img width="761" alt="grafik" src="https://github.com/cschroeter/park-ui/assets/1846056/e63ba9f7-ba74-426d-a139-3d5b877f56ac">

**Comment by gurkerl83** [comment]
There are multiple implementations in the repo. I used the tailwind react version. I try again tomorrow. Thx!

**Comment by cschroeter** [comment]
@sholzmayer cc

**Comment by gurkerl83** [comment]
Ok, used the latest one, the component does not complain and finds the function onInputValueChange but the type is `onInputValueChange: any`

**Comment by gurkerl83** [comment]
I have create a sandbox which illustrates the problem. https://codesandbox.io/s/awesome-moon-qlcvdw 
Thx!

**Comment by cschroeter** [comment]
@sholzmayer can you update the `create-style-context` in Tailwind to match the newer version in Panda?

**Comment by gurkerl83** [comment]
I think I tried that, but the implementations are different, just replacing it is not enough, I will give it another try.

**Comment by cschroeter** [comment]
@gurkerl83 

Yes! It is pretty clear what we have to do. The screenshot above is using the Panda version of that script and that works so there should be no reason that the Tailwind version does not work ;)

**Comment by sholzmayer** [comment]
@gurkerl83 thanks a lot for your issue; I'll have a look at it and fix it :)

**Comment by sholzmayer** [comment]
while having a look at the tailwind react implementation of the context (which has also other type issues as well), I noticed, that there is also an issue with the panda one: #91. 
Just posting it here for reference.

**Comment by sholzmayer** [comment]
@gurkerl83 confirming your initial report being fixed, not having the ark prop onInputValueChange, see here:

<img width="453" alt="image" src="https://github.com/cschroeter/park-ui/assets/20296626/86b27567-1142-4e6c-81d5-5e5b2e0f34ff">

I've updated the storybook and the examples

**Comment by gurkerl83** [comment]
@sholzmayer Thx, just a quick question why are there several versions of the same thing, kind of hard to maintain?

**Comment by sholzmayer** [comment]
It's a copy in the standalone examples (which are not part of the mono repo). It will be easier to maintain / upgrade, as soon as the CLI is there. Stay tuned.

**Comment by gurkerl83** [comment]
Ok, I can confirm that is see this now in intelli sense,
In the example for combobox there is a width used like here

```
<Combobox.Root width="2xs" onInputValueChange={handleChange} items={items}>
```

I don`t see this anymore?

**Comment by sholzmayer** [comment]
In Park tailwind you need to use the width as a class-name, there aren't any style props like in panda. If you had it there before, this would not have worked.
