### ISSUE TITLE
Inconsistency between Park-UI documentation and Ark-UI 1.0 API

### ISSUE THREAD

**Issue by kaumac** [cschroeter/park-ui#88]
Some components (I'm not using many yet, so this is the first one I have problems with) have a different API on the Park-UI documentation than the one available on the Ark-UI documentation.

For example on the Park-UI documentation for **RadioButtonGroup** there's `export const RadioButtonGroupItem = withContext(styled(Ark.RadioGroup.Radio), 'item')` but Ark-UI does not export a **Ark.RadioGroup.Item** component, it only has **Ark.RadioGroup.Radio** which I assume is the correct one?

I'm using the latest version of Ark-UI, PandaCSS and Park-UI

**Comment by kaumac** [comment]
My bad, it was some weird cache issue on my environment. Closing this.

Thanks for the 1.0 update!

**Comment by cschroeter** [comment]
@kaumac 

You're welcome. There will be a few rough edges for the next few days but we will get there :)
