### ISSUE TITLE
There was a Range Slider component. Now it is gone.

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#90]

**Comment by coopbri** [comment]
@juliomuhlbauer  the `RangeSlider` component was deprecated in favor of the regular `Slider` component: https://github.com/cschroeter/park-ui/blob/main/packages/panda/CHANGELOG.md#removed

You can achieve what you need with multiple `SliderThumb`s. Let me know if you have trouble getting it to work

**Comment by cschroeter** [comment]
Thanks @coopbri 

I will add an example to the slider component docs.
