### ISSUE TITLE
IntelliSense for panda react not raising type issues for invalid props

### ISSUE THREAD

**Issue by sholzmayer** [cschroeter/park-ui#91]
The IntelliSense is working fine for panda react, but it's not giving any type errors, when other props are used (see 2nd very long prop):
 
<img width="599" alt="image" src="https://github.com/cschroeter/park-ui/assets/20296626/56f1ee40-f7c9-4a4e-bd16-be10addef9d3">

**Comment by cschroeter** [comment]
<img width="762" alt="grafik" src="https://github.com/cschroeter/park-ui/assets/1846056/585ca2a5-c502-43da-b7e4-6f9a06c92180">

@sholzmayer 

Thanks for creating this issue. Should be fixed by now.
