### ISSUE TITLE
Accordion ItemContent requires a wrapper element though Ark UI not

### ISSUE THREAD

**Issue by BorisZubchenko** [cschroeter/park-ui#92]
Comparing an example from [Accordion | Ark UI](https://ark-ui.com/docs/components/accordion):
```tsx
  <Accordion.ItemContent>{item} content</Accordion.ItemContent>
```
And Park UI:
```tsx
  <Accordion.ItemContent>
    <div>
      Pudding donut gummies chupa chups oat cake marzipan biscuit tart. Dessert macaroon ice
      cream bonbon jelly. Jelly topping tiramisu halvah lollipop.
    </div>
  </Accordion.ItemContent>
```
We see, that Park UI requires a `div` to be present (stylings don't work properly without it).

I think that we should be able to provide content without any wrapper.

**Comment by cschroeter** [comment]
@BorisZubchenko 

Thanks for taking your time to create this issue. This is a non breaking temporary workaround until we have a propper [collapsible maschine](https://github.com/chakra-ui/zag/pull/986) from Zag / Ark UI.


```js
// the workaround
{
  itemContent: {
      display: 'grid',
      gridTemplateRows: '0fr',
      transitionProperty: 'grid-template-rows, padding-bottom',
      transitionDuration: 'normal',
      transitionTimingFunction: 'default',
      _open: {
        gridTemplateRows: '1fr',
      },
      '& > div': {
        overflow: 'hidden',
      },
    }
}
```
