### ISSUE TITLE
[Dialog] Scrollbar causing layout shift

### ISSUE THREAD

**Issue by joepetrillo** [cschroeter/park-ui#94]
https://github.com/cschroeter/park-ui/assets/32227357/f83344de-fcee-4d65-b44b-cb906d8a1fb3

**Comment by cschroeter** [comment]
@joepetrillo 

Thanks for taking your time to report this issue. It should be good now :)


https://github.com/cschroeter/park-ui/assets/1846056/c17c751e-66bf-445a-9a8f-f3544cbcb8c5
