### ISSUE TITLE
[Drawer] Minor scrollbar layout shift when on right side

### ISSUE THREAD

**Issue by joepetrillo** [cschroeter/park-ui#96]
The scrollbar appears before the close animation finishes, so we see a very quick layout shift. When compared to the left side, which closes very smoothly, it is more noticeable.

https://github.com/cschroeter/park-ui/assets/32227357/87a5e281-fc24-49d1-b9ca-ef838e5afb89

**Comment by cschroeter** [comment]
@joepetrillo 

Yes that is correct and I spend some time to see if this can be improved but I don't think there is besides having a faster timing on the closing animation to make this less noticable. 

For reference even the great [Material UI](https://mui.com/material-ui/react-drawer/) has the same issue. So I will as sad as it is, mark this as won't fix.
